Add separator new lines, sync other changes

diff --git a/system/xbin/mcc b/system/xbin/mcc
--- a/system/xbin/mcc
+++ b/system/xbin/mcc
@@ -21,44 +21,46 @@
 
 ( (
 if ! id | grep '^uid=0' >/dev/null; then su -c mcc "$@"; exit; fi;
+
 mod_dir=/not/yet/set;
 ver_log=/dev/null; err_log=/dev/null;
+
 if [ ! -d "$mod_dir" ]; then
     echo -e 'mcc: error: Failed to detect MOUNTPOINT\n'; exit;
 elif [ ! $no_ver_logs ]; then
     ver_log=$mod_dir/files/main.log; err_log=$mod_dir/files/main_err.log;
 fi;
+
 ( ( (
 set -x 2>$ver_log; echo -ne '\n';
+
 lock_file=$mod_dir/lock;
 files_dir=$mod_dir/files;
+yielder=$files_dir/yield_s;
 config=$files_dir/secure/mcc.conf;
+
 export PATH=$mod_dir/busybox:$PATH;
 if (! busybox | grep 'topjohnwu ' || ! which awk) >/dev/null; then
     echo -e 'mcc: error: Failed to set BusyBox up\n'; exit;
 fi;
+
 abort() { echo "mcc: error: $1" >&2; echo -e "mcc: error: $1\n"; exit; }
 printp() { echo -e "mcc: info: $1\n"; }
-warn() { echo -e "mcc: warning: $1\n"; }
+
 exxit_() { head -101 $mod_dir/docs/README.md; exit; }
+
 get_prop() { sed -n "s/^$1=//p" $2 $config; }
 set_prop() { sed -i "s|^$1=.*|$1=$2|g" $config; }
-get_cpid() {
-    for pid in $(ps | awk "!/ awk / && / $1$/{ print \$1 }"); do
-        case $(awk '/^PPid: /{ print $2 }' /proc/$pid/status) in
-            $$) echo $pid; break; ;;
-        esac;
-    done;
-}
+get_spid() { ps | awk "!/ awk / && / {mcc} / && / --sleep $1$/{ print \$1 }"; }
+
+is_runningd() { ps | awk '!/ awk / && / {mcc} / && / --launch-daemon$/'; }
 is_charging() {
     case $1 in
         cur) test $(get_prop POWER_SUPPLY_CURRENT_NOW $(uevent_f)) -le 0; ;;
         *  ) grep -q '^POWER_SUPPLY_STATUS=[Cc]harging$' $(uevent_f);     ;;
     esac;
 }
-is_runningd() {
-    ps | awk '!/ awk / && / {mcc} / && / --launch-daemon$/' | grep -vq "^ *$$ ";
-}
+
 test_bound() {
     if [[ $1 -le 0 || $1 -ge 100 ]]; then
         abort 'A threshold must belong to 1 - 99';
@@ -75,10 +77,12 @@ test_diff() {
         abort 'Thresholds must keep 5 levels difference';
     fi;
 }
+
 test_boundaries() {
-    if [[ ( (! -z $2 && ($1 -lt 15 || $2 -lt 15 || $1 -gt 85 || $2 -gt 85)) || ($1 -lt 20 || $1 -gt 85)) && \
-          ! $enforce ]]; then
+    if [[ ( (! -z $2 && ($1 -lt 15 || $2 -lt 15 || $1 -gt 85 || $2 -gt 85)) || ($1 -lt 20 || $1 -gt 85)) \
+       && ! $enforce ]]; then
         abort 'Threshold(s) must belong to 15 - 85';
+
     elif [[ $1 -ge 25 ]]; then
         d=$(($1 - 10));
     elif [[ $1 -ge 20 ]]; then
@@ -90,24 +94,31 @@ test_boundaries() {
     else
         d=1;
     fi;
+
     if [[ -z $u ]]; then u=$1; fi; set_prop up_threshold $u;
     if [[ -z $d ]]; then d=$2; fi; set_prop down_threshold $d;
     printp 'New values saved';
 }
+
 charge_init() {
-    if ps | awk '!/ awk / && / {mcc} / && / (--enable|-e|--disable|-d) ?' | grep -vq "^ *$$ "; then
+    if [[ -f $yielder ]]; then
         abort 'Another session is already running';
     elif [[ ! -f $lock_file ]]; then
         touched=true;
     fi;
-    re_count; touch $lock_file;
+
+    re_count; touch $lock_file $yielder;
     switch_ $turn_1;
 }
+
 charge_loop() { while eval $1; do switch_ $turn_1; sleep 1; done; }
+
 re_count() { set_prop superceded_yet 0; }
+
 write_() {
     for i in 1 2; do
         switch=$(get_prop switch_$i | awk '{ print $1 }');
+
         if [[ $switch != dummy_Switch ]]; then
             case $1 in
                 ON ) get_prop switch_$i | awk '{ print $2 }' >$switch; ;;
@@ -116,44 +127,56 @@ write_() {
         fi;
     done;
 }
+
 switch_() {
     case $1 in
         ON ) test='! is_charging'; val_1=OFF; val_2=ON;  ;;
         OFF) test='is_charging';   val_1=ON;  val_2=OFF; ;;
     esac;
+
     for i in 1 2 3 4 5 6 7 8 9 10 11; do
+
         if eval $test; then
             write_ $val_1; sleep 1; $val_2; unset switched;
+
         elif test ! $switched && eval "$test cur"; then
             if [[ $(superceded_yet) -lt 10 ]]; then
                 set_prop superceded_yet $(($(superceded_yet) + 1));
             else
                 write_ $val_1; sleep 1; $val_2;
             fi;
+
         else
             switched=true; re_count; break;
         fi;
         sleep 1;
     done;
 }
+
 toggle() {
     value=true; status=ON; if $($1); then value=false; status=OFF; fi;
     set_prop $1 $value;
     printp "$2 toggled $status";
 }
+
 auto_shut() { get_prop auto_shut; }
 auto_switch() { get_prop auto_switch; }
+
 up_threshold() { get_prop up_threshold; }
 down_threshold() { get_prop down_threshold; }
 shut_threshold() { get_prop shut_threshold; }
+
 superceded_yet() { get_prop superceded_yet; }
+
 batt_level() { get_prop POWER_SUPPLY_CAPACITY $(uevent_f); }
 uevent_f() { get_prop uevent; }
+
 c_session() {
     case $1 in
         enable ) turn_1=ON;  turn_2=OFF; text=enabled;  ;;
         disable) turn_1=OFF; turn_2=ON;  text=disabled; ;;
     esac;
+
     if [[ ! -z $2 ]]; then
         if echo $2 | grep -Eq '^[0-9]+%$'; then
             level=$(echo $2 | tr -d %);
@@ -161,26 +184,34 @@ c_session() {
             charge_init;
             printp "Session charging $text until $2...";
             charge_loop '[[ ! $(batt_level) -eq $level ]]';
+
         elif echo $2 | grep -Eq '^[0-9]+[smh]$'; then
             charge_init;
             printp "Session charging $text for $2...";
-            setsid sleep $2;
-            sleep_pid=$(get_cpid "sleep $2");
+            no_ver_logs=true mcc --sleep $2;
+            sleep_pid=$(get_spid $2);
             charge_loop 'ps | grep -q "^ *$sleep_pid "';
+
         else
             abort 'Invalid argument format';
         fi;
-        re_count; if [[ $touched ]]; then rm -f $lock_file; fi;
+
+        re_count;
+        rm -f $yielder; if [[ $touched ]]; then rm -f $lock_file; fi;
         switch_ $turn_2;
         printp 'Session ended';
+
     else
         charge_loop ':';
     fi;
 }
+
 if [[ ! -f $(uevent_f) || ! -f $(get_prop switch_1 | awk '{ print $1 }') ]]; then
     abort 'mcc internals are not properly configured';
 fi;
+
 case $1 in -f|--force) enforce=true; shift; ;; esac;
+
 case $1 in
     -p|--shut)
         if [[ -z $2 ]]; then
@@ -190,10 +221,12 @@ case $1 in
         elif [[ ($2 -gt 20 || $2 -lt 5) && ! $enforce ]]; then
             abort 'Threshold must belong to 5 - 20';
         fi;
+
         test_bound $2;
         set_prop shut_threshold $2;
         printp 'New value saved';
     ;;
+
     -s|--switch)
         if [[ ! -z $3 ]]; then
             test_level $3; test_level $2;
@@ -204,43 +237,49 @@ case $1 in
             else
                 abort 'Thresholds must be different';
             fi;
+
         elif [[ ! -z $2 ]]; then
             test_level $2; test_boundaries $2;
+
         else
             abort 'Threshold(s) must be given';
         fi;
     ;;
+
     -rt|--default)
         set_prop up_threshold 80; set_prop down_threshold 70;
         set_prop shut_threshold 20;
         printp 'All thresholds are reverted to defaults';
     ;;
-    -tp|--auto-shut)
-        toggle auto_shut 'Auto shut';
-    ;;
-    -ts|--auto-switch)
-        toggle auto_switch 'Auto switch';
-    ;;
-    -e|--enable ) c_session enable  $2; ;;
-    -d|--disable) c_session disable $2; ;;
+
+    -tp|--auto-shut  ) toggle    auto_shut   'Auto shut';   ;;
+    -ts|--auto-switch) toggle    auto_switch 'Auto switch'; ;;
+
+    -e|--enable      ) c_session enable      $2;            ;;
+    -d|--disable     ) c_session disable     $2;            ;;
+
     -rd|--re-daemon)
         if ! $(auto_shut) && ! $(auto_switch); then
             abort 'Neither auto switch or auto shut is ON';
+        elif is_runningd; then
+            abort 'mcc daemon is already running';
         fi;
-        if is_runningd; then abort 'mcc daemon is already running'; fi;
+
         no_ver_logs=true mcc --launch-daemon </dev/null >/dev/null 2>&1;
         if ! is_runningd; then abort 'Failed to launch the daemon'; fi;
         printp 'mcc daemon is running now';
     ;;
+
     --launch-daemon)
-        if is_runningd; then abort 'mcc daemon is already running'; fi;
         while $(auto_shut) || $(auto_switch); do
             if [[ ! -f $lock_file ]]; then
+
                 if $(auto_shut); then
                     if test $(batt_level) -le $(shut_threshold) && ! is_charging; then
                         setprop sys.powerctl shutdown;
                     fi;
                 fi;
+
                 if $(auto_switch); then
                     if [[ $(batt_level) -le $(down_threshold) ]]; then
                         switch_ ON;
@@ -252,37 +291,45 @@ case $1 in
             sleep 1;
         done;
     ;;
+
     -r|--rm-stats)
         dumpsys batterystats --reset >/dev/null 2>&1;
         rm -f /data/system/batterystats.bin;
         printp 'Battery stats are reset';
     ;;
+
     -c|--clean)
-        kill $(ps | awk "!/ awk / && / {mcc} / && !/^ *$$ /{ print \$1 }" | tr '\n' ' ');
         re_count;
         rm -f $files_dir/* $lock_file;
-        printp 'Everything cleaned up';
+        kill $(ps | awk '!/ awk / && / {mcc} /{ print $1 }' | tr '\n' ' ');
     ;;
+
+    --sleep) sleep $1; ;;
+
     -i|--info)
         echo -e '- Battery status\n';
         echo "-- battery level: $(batt_level)";
         echo "-- battery health: $(get_prop POWER_SUPPLY_HEALTH $(uevent_f))";
         status='Not charging'; if is_charging; then status=Charging; fi;
         echo -e "-- charging status: $status\n";
+
         echo -e '- Current settings\n';
         echo "-- up threshold: $(up_threshold)";
         echo "-- down threshold: $(down_threshold)";
         echo -e "-- shut threshold: $(shut_threshold)\n";
+
         status=OFF; if $(auto_switch); then status=ON; fi;
         echo "-- automatic switching: $status";
         status=OFF; if $(auto_shut); then status=ON; fi;
         echo -e "-- automatic power-off: $status\n";
+
         status='Not running'; if is_runningd; then status=Running; fi;
         echo -e "- Daemon status: $status\n";
     ;;
+
     -h|--help) exxit_; ;;
     *)
-        warn 'Invalid argument(s)'; sleep 2;
+        echo -e 'mcc: warning: Invalid argument(s)\n'; sleep 2;
         exxit_;
     ;;
 esac;
