Release code 201803051

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,26 +1,25 @@
 #!/sbin/sh
 # MC's Charging Controller
-# mcc Installer ( 201802281 )
+# mcc Installer ( 201803051 )
 # MCMotherEffin' @ XDA Developers
 
 # Copyright (c) 2018 Jaymin " MCMotherEffin' " Suthar. All rights reserved.
 
 # This file is a part of the project "MC's Charging Controller ( mcc )"
 
-# I MCMotherEffin', hereby announce that "MC's Charging Controller"
+# I MCMotherEffin', hereby declare that "MC's Charging Controller"
 ## is licensed under the GNU GPL v3 and you are allowed to modify or
 ## re-distribute it under the terms of the GNU GPL v3 as published by
-## the Free Software Foundation or any later version
+## the Free Software Foundation or any later version provided that you
+## include the above copyright notice and this declaration
 
-# Given the above rights, you are required to inform me of
-## 1) any modifications ( public / private ) you do and / or
-## 2) if you re-distribute it ( which is definitely public )
+# Given the above rights, you are required to inform me
+## if you re-distribute it ( wherever you do, it is public )
 ## you should do so by sending me a Private Message at xda-developers.com
-## Finally, you should obtain a copy of the GNU GPL v3 from <http://gnu.org/licenses/>
+
+# Finally, you should obtain a copy of the GNU GPL v3 from <http://gnu.org/licenses/>
 
 if grep '^/sbin/sh' </proc/$$/cmdline >/dev/null; then
-
-    # Abort recovery installation, kernel issues
     fd=/proc/self/fd/$2;
 
     ui_print() { echo -e "ui_print $1\nui_print" >>$fd; };
@@ -29,20 +28,18 @@ if grep '^/sbin/sh' </proc/$$/cmdline >/dev/null; then
     ui_print '- Abort :- Please install in boot mode';
     ui_print ' ';  ui_print ' ';
     exit 1;
+elif [ $(magisk -V) -lt 1400 ]; then
+    echo -e "\n\nAbort :- Please install Magisk >= 1400\n"; exit 1;
 fi;
 echo -e "\n\n";
 
-# Define variables ( not all )
+# Define universal functionals
 zip_file="$3";
-
-# Define functions ( not all )
 
 abort() { echo -e "- Abort :- $1\n"; exit 1; };
 
-# Get the system minding A / B devices
+# Find BusyBox, Magisk mountpoint and set BusyBox applets up
 system=/system; if [ -d /system_root ]; then system=/system_root/system; fi;
-
-# Find BusyBox and Magisk mount point
 for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$;); do
     if $magisk_bb | grep 'topjohnwu ' >/dev/null; then
         image=${magisk_bb%/*/*}/magisk.img;
@@ -64,13 +61,10 @@ done;
 if [ -z $magisk_bb -o -z $real_mount_point ]; then
     abort 'Could not set environment based on Magisk';
 fi;
-
-# Set BusyBox up ( using hardlinks )
 tmp_dir=/dev/mcc_tmp;
 tmp_bin=$tmp_dir/busybox;
 rm -rf $tmp_bin; mkdir -p $tmp_bin;
-cp -a $magisk_bb $tmp_bin;
-$tmp_bin/busybox --install $tmp_bin;
+$magisk_bb --install -s $tmp_bin/;
 export PATH=$tmp_bin:$PATH;
 
 # Print module banner
@@ -85,13 +79,13 @@ echo -e "- Please make sure the device is charging\n";
 sleep 5;
 echo -e "- Checking compatibility...\n";
 tmp_file=$tmp_dir/cached;
-find /sys/devices /sys/module -type f -name uevent >$tmp_file;
+find -L /sys/class /sys/devices /sys/module -type f -name uevent >$tmp_file;
 
-is_charging() { grep -q ^POWER_SUPPLY_STATUS=Charging$ $uevent; };
+is_charging() { grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $uevent; };
 
 while read uevent; do
     chmod u+r $uevent;
-    if grep -q ^POWER_SUPPLY_NAME=.*batt.*$ $uevent && is_charging; then
+    if grep -q ^POWER_SUPPLY_NAME=.*[Bb]att.*$ $uevent && is_charging; then
         i=1;
         for ref in ${uevent%/*}/*; do
             if [[ -f $ref ]]; then
@@ -102,42 +96,21 @@ while read uevent; do
                 continue;
             fi; chmod u+r $ref;
             case $(cat $ref) in
-                1       )
-                    echo 0 >$ref;        c_ON=1;        c_OFF=0;
-                ;;
-                0       )
-                    echo 1 >$ref;        c_ON=0;        c_OFF=1;
-                ;;
-                on      )
-                    echo off >$ref;      c_ON=on;       c_OFF=off;
-                ;;
-                off     )
-                    echo on >$ref;       c_ON=off;      c_OFF=on;
-                ;;
-                true    )
-                    echo false >$ref;    c_ON=true;     c_OFF=false;
-                ;;
-                false   )
-                    echo true >$ref;     c_ON=false;    c_OFF=true;
-                ;;
-                enable  )
-                    echo disable >$ref;  c_ON=enable;   c_OFF=disable;
-                ;;
-                disable )
-                    echo enable >$ref;   c_ON=disable;  c_OFF=enable;
-                ;;
-                enabled )
-                    echo disabled >$ref; c_ON=enabled;  c_OFF=disabled;
-                ;;
-                disabled)
-                    echo enabled >$ref;  c_ON=disabled; c_OFF=enabled;
-                ;;
-                *       )
-                    continue;
-                ;;
-            esac; usleep 10000;
+                1       ) c_ON=1;        c_OFF=0;        ;;
+                0       ) c_ON=0;        c_OFF=1;        ;;
+                on      ) c_ON=on;       c_OFF=off;      ;;
+                off     ) c_ON=off;      c_OFF=on;       ;;
+                true    ) c_ON=true;     c_OFF=false;    ;;
+                false   ) c_ON=false;    c_OFF=true;     ;;
+                enable  ) c_ON=enable;   c_OFF=disable;  ;;
+                disable ) c_ON=disable;  c_OFF=enable;   ;;
+                enabled ) c_ON=enabled;  c_OFF=disabled; ;;
+                disabled) c_ON=disabled; c_OFF=enabled;  ;;
+                *       ) continue;                      ;;
+            esac;
+            echo $c_OFF >$ref; usleep 100000;
             if ! is_charging; then
-                echo $c_ON >$ref; usleep 10000;
+                echo $c_ON >$ref; usleep 100000;
                 if is_charging; then
                     eval switches_$i=\"$ref $c_ON $c_OFF\"; let i++;
                     if [[ $i -eq 3 ]]; then break 2; fi;
@@ -149,11 +122,11 @@ while read uevent; do
     fi;
 done <$tmp_file;
 if [[ $i -eq 1 ]]; then
-    abort "Your device don't support these functionalities";
+    abort 'Your device does not support these functionalities';
 fi;
 echo -e "- OK\n\n\n";
 
-# Create or resize image for installation
+# Get image ready and mounted for un-installation
 image=${image%/*}/magisk_merge.img;
 if [[ -f $image ]]; then
     echo -e "- $image exists\n";
@@ -166,100 +139,70 @@ if [[ -f $image ]]; then
     img_total=$(imgsize_test 2);
     if [[ $(imgsize_test 1) -eq $img_total ]]; then
         echo -e "- Expanding $image...\n";
-        resize2fs $image $((img_total + 64))M;
+        resize2fs $image $((img_total + 32))M;
     fi;
 else
     echo -e "- Creating $image...\n";
     make_ext4fs -l 64M $image >&2;
 fi;
-
-is_mounted() { grep -q " $mount_point " /proc/mounts; };
-
-# Mount the image
 echo -e "- Mounting $image...\n";
 mount_point=/dev/mcc_img;
 mkdir $mount_point;
-for minor in 0 $(seq -s ' ' 7); do
+
+is_mounted() { grep -q " $mount_point " /proc/mounts; };
+
+for minor in $(seq -s ' ' 7); do
     loop_device=/dev/block/loop$minor;
     if [[ ! -b $loop_device ]]; then mknod $loop_device b 7 $minor; fi;
     if losetup $loop_device $image; then
-        mount -t ext4 -o loop $loop_device $mount_point;
+        mount -t ext4 -o rw,noatime $loop_device $mount_point;
     fi;
     if is_mounted; then break; fi;
 done;
 if ! is_mounted; then abort "Could not mount $image"; fi;
 
-get_prop() { sed -n s/^$1=//p $2; };
-
-# Proceed to install / uninstall
+# Proceed to un-installation
 mod_dir=$mount_point/mcc; inst_mod_dir=$real_mount_point/mcc;
+
+get_prop() { sed -n s/^$1=//p $2; };
 
 which_installed() { get_prop versionCode $inst_mod_dir/module.prop || echo 0; };
 
-if [[ $(get_prop versionCode $mod_dir/module.prop || echo $(which_installed)) -ge 201802281 ]]; then
+if [[ $(get_prop versionCode $mod_dir/module.prop || echo $(which_installed)) -ge 201803051 ]]; then
 
     # Uninstall
     echo -e "- Same or newer already installed\n";
-    echo -e "- Attention :- Uninstalling...\n";
-
+    echo -e "- Attention :- Performing a complete uninstall...\n";
     rm -rf $mod_dir $inst_mod_dir /cache/mcc_e*.log;
-    for proc_id in $(ps | grep -v ' grep ' | grep ' {mcc} ' | awk '{ print $1 }';); do
-        kill $proc_id;
-    done;
+    kill $(ps | grep -v ' grep ' | grep ' {mcc} ' | awk '{ print $1 }' | tr '\n' ' ';);
     if inst_mcc=$(ls $system/xbin/mcc || ls $system/bin/mcc); then
         if [[ $(magisk -V) -ge 1410 ]]; then
             umount $inst_mcc; rm -f $inst_mcc; umount ${inst_mcc%/*};
-        else
-            echo '#!/system/bin/sh' >$inst_mcc; echo "echo \"It's uninstalled\"" >>$inst_mcc;
         fi;
     fi;
 else
 
     # Install
-
-    # Create all needed directories
     rm -rf $mod_dir; mkdir -p $mod_dir/docs $mod_dir/cache;
-
-    # Extract module files
     echo -e "- Extracting module files...\n";
     unzip -o "$zip_file" 'system/*' mcc.conf service.sh module.prop -d $mod_dir >&2;
-    unzip -o "$zip_file" LICENSE.md README.md -d $mod_dir/docs >&2;
+    unzip -o "$zip_file" README.md -d $mod_dir/docs >&2;
     bin_dir=$mod_dir/system/xbin;
     if [[ ! -d $system/xbin ]]; then
-
-        # Target tree missing from system root
-        ## thus, Magic Mounting can be too dangerous
-        ## according to a conversation between @topjohnwu and @rovo89
-        ## So, install mcc in system binaries directory
-        ## for it is guaranteed to exist
-
-        # An important thing
-        ## some devices ( Samsung ) don't like adding to system binaries
-        ## ( maybe they need those binaries live while Magic Mounting happens )
-        ## a workaround for that is to install mcc in /sbin
-        ## but, doing that seem to break MagiskHide policies
-        ## to prevent that, we should possibly see SuperSU's BINDSBIN code
-        ## which I'm currently unable to adapt to this module
-        ## So, that's currently not available
-        mv $bin_dir $mod_dir/system/bin;
-        bin_dir=$mod_dir/system/bin;
+        mv $bin_dir $mod_dir/system/bin; bin_dir=$mod_dir/system/bin;
     fi;
 
     set_prop() { sed -i "s|^$1=.*|$1=$2|g" $mod_dir/mcc.conf; };
 
-    # Don't restore confs for this old versions
     if [[ $(which_installed) -ge 201802251 ]]; then
         if old_conf=$(ls $inst_mod_dir/mcc.conf); then
 
-            # Restore settings
-            echo -e "- Restoring settings...\n";
+            echo -e "- Restoring configurations...\n";
             for prop in auto_shut auto_switch daemon_mode up_threshold down_threshold shut_threshold; do
                 set_prop $prop $(get_prop $prop $old_conf);
             done;
         fi;
     fi;
-
-    # Set uevent and switches in mcc.conf
     set_prop uevent $uevent;
     for i in 1 2; do
         switch="$(eval echo \$switch_$i)";
@@ -268,11 +211,7 @@ else
             * ) set_prop switch_$i "$switch"; ;;
         esac;
     done;
-
-    # Enable Magic Mount
     touch $mod_dir/auto_mount;
-
-    # Update info for Magisk Manager
     mkdir $inst_mod_dir;
     touch $inst_mod_dir/update;
     cp -f $mod_dir/module.prop $inst_mod_dir;
@@ -289,16 +228,13 @@ else
         done;
     };
 
-    # Set permissions
     echo -e "- Setting permissions...\n";
     set_perm_recursive $mod_dir    0 0644;
     set_perm_recursive $bin_dir 2000 0755;
 fi;
 
-# Unmount the image
+# Finalize
 umount $mount_point; losetup -d $loop_device;
-
-# Cleanup
 rmdir $mount_point; rm -rf $tmp_dir;
 echo -e "- Done\n\n\n";
 exit 0;
diff --git a/system/xbin/mcc b/system/xbin/mcc
--- a/system/xbin/mcc
+++ b/system/xbin/mcc
@@ -1,40 +1,37 @@
 #!/system/bin/sh
 # MC's Charging Controller
-# mcc Main ( 201802281 )
+# mcc Main ( 201803051 )
 # MCMotherEffin' @ XDA Developers
 
 # Copyright (c) 2018 Jaymin " MCMotherEffin' " Suthar. All rights reserved.
 
 # This file is a part of the project "MC's Charging Controller ( mcc )"
 
-# I MCMotherEffin', hereby announce that "MC's Charging Controller"
+# I MCMotherEffin', hereby declare that "MC's Charging Controller"
 ## is licensed under the GNU GPL v3 and you are allowed to modify or
 ## re-distribute it under the terms of the GNU GPL v3 as published by
-## the Free Software Foundation or any later version
+## the Free Software Foundation or any later version provided that you
+## include the above copyright notice and this declaration
 
-# Given the above rights, you are required to inform me of
-## 1) any modifications ( public / private ) you do and / or
-## 2) if you re-distribute it ( which is definitely public )
+# Given the above rights, you are required to inform me
+## if you re-distribute it ( wherever you do, it is public )
 ## you should do so by sending me a Private Message at xda-developers.com
-## Finally, you should obtain a copy of the GNU GPL v3 from <http://gnu.org/licenses/>
 
+# Finally, you should obtain a copy of the GNU GPL v3 from <http://gnu.org/licenses/>
+
+# Pre-exec operations
 if ! id | grep uid=0 >/dev/null; then
-
-    # Make sure mcc is running as root
     su -c mcc "$@"; exit $?;
-elif test ! $no_file_logs && test ! $no_err_log; then
-
-    # Re-direct all the errors to logfile
-    no_err_log=true mcc "$@" 2>/cache/mcc_err.log; exit $?;
+elif [ ! $no_file_logs ]; then
+    if [ ! $no_err_logs ]; then
+        no_err_logs=true mcc "$@" 2>/cache/mcc_err.log; exit $?;
+    fi;
+    set -x 2>/cache/mcc_env.log;
 fi;
-
-if [ ! $no_file_logs ]; then set -x 2>/cache/mcc_env.log; fi;
 echo ' ';
 
-# Get the system minding A / B devices
+# Find BusyBox, Magisk mountpoint and set BusyBox applets up
 system=/system; if [ -d /system_root ]; then system+=_root/system; fi;
-
-# Find BusyBox and Magisk mount point
 for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$;); do
     if $magisk_bb | grep 'topjohnwu ' >/dev/null; then
         image=${magisk_bb%/*/*}/magisk.img;
@@ -56,53 +53,38 @@ done;
 if [ -z $magisk_bb -o -z $mount_point ]; then
     echo -e "- Abort :- Could not set environment based on Magisk\n"; exit 1;
 fi;
-
-# Set BusyBox up ( using hardlinks )
 mod_dir=$mount_point/mcc;
 mcc_bin=$mod_dir/busybox;
-rm -rf $mcc_bin/.;
-cp -a $magisk_bb $mcc_bin;
-$mcc_bin/busybox --install $mcc_bin;
+rm -rf $mcc_bin; mkdir $mcc_bin;
+$magisk_bb --install -s $mcc_bin/;
 export PATH=$mcc_bin:$PATH;
 
-# Define variables ( not all )
+# Define universal functionals ( not all )
 cache_dir=$mod_dir/cache;
 config=$mod_dir/mcc.conf;
 ver_log=$cache_dir/verbose.log;
 
-# Define functions
-
-## logs / yields an error and exits 1
-
 abort() {
-    echo -e "\n\n- Fatal error - message --> '$1'" >>/cache/mcc_err.log;
+    echo -e "\n- Fatal error --> '$1'" >>/cache/mcc_err.log;
     echo -e "- Abort :- $1\n";
     exit 1;
 };
-
-## gets a property from a prop file
 
 get_prop() {
     prop_file=$config; if [[ ! -z $2 ]]; then prop_file=$2; fi;
     sed -n s/^$1=//p $prop_file;
 };
 
-## sets a property in a prop file
-
 set_prop() {
     prop_file=$config; if [[ ! -z $3 ]]; then prop_file=$3; fi;
     sed -i "s|^$1=.*|$1=$2|g" $prop_file;
 };
-
-## tests whether the argument belongs to 0 - 100
 
 test_bound() {
     if [[ $1 -le 0 || $1 -ge 100 ]]; then
         abort 'Please give a level between 0 - 100';
     fi;
 };
-
-## tests whether the argument is a battery level
 
 test_level() {
     if echo $1 | grep -Eq ^[0-9]+$; then
@@ -112,15 +94,43 @@ test_level() {
     fi;
 };
 
-## tests whether arguments are not so close
-
 test_diff() {
     if [[ ! $1 -ge $(($2 + 5)) && ! $force ]]; then
-        abort "Please don't give this close thresholds";
+        abort "Please do not give this close thresholds";
     fi;
 };
 
-## toggles the prop true / false
+test_switch() { if eval $test; then switch_ $turn_1; fi; };
+
+charge_acts() {
+    if $(auto_switch); then set_prop auto_switch false; overridden=true; fi;
+    test_switch;
+};
+
+is_charging() { grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $(uevent_f); };
+
+is_runningd() {
+    ps | grep -v ' grep ' | grep ' root ' | grep ' {mcc} ' | grep -q ' --launch-daemon$';
+};
+
+are_refs_set() {
+    test $(uevent_f) != dummy_Events && test $(get_prop switch_1) != dummy_Switch;
+};
+
+reset_perms() {
+    if are_refs_set; then
+        chmod u+r $(uevent_f) $(get_prop switch_1 | awk '{ print $1 }');
+        sec_switch=$(get_prop switch_2 | awk '{ print $1 }');
+        if [[ $sec_switch != dummy_Switch ]]; then chmod u+r $sec_switch; fi;
+    fi;
+};
+
+reset_stats() {
+    echo -e "- Resetting battery statistics...\n";
+    dumpsys batterystats --reset >/dev/null;
+    if [[ $1 == rm ]]; then rm -f /data/system/batterystats.bin; fi;
+    echo -e "- Done\n";
+};
 
 toggle() {
     value=true; status=ON; if $($1); then value=false; status=OFF; fi;
@@ -139,8 +149,6 @@ show_help() {
     exit 1;
 };
 
-## turns charging ON / OFF
-
 switch_() {
     for i in 1 2; do
         switch=$(get_prop switch_$i | awk '{ print $1 }');
@@ -157,8 +165,6 @@ switch_() {
     done;
 };
 
-## tests and sets references
-
 test_refs() {
     if ! are_refs_set; then
         echo -e "Attention :- No references set\n";
@@ -166,30 +172,15 @@ test_refs() {
     fi;
 };
 
-## tests and makes daemon run
-
 test_daemon() {
     if ! is_runningd; then
-        echo -e "- mcc daemon is not running, forking it...\n";
-        ( no_file_logs=true mcc --launch-daemon </dev/null >/dev/null 2>&1 & );
+        echo -e "- mcc daemon is not running, launching it...\n";
+        (no_file_logs=true mcc --launch-daemon </dev/null >/dev/null 2>&1 &);
         echo -e "- It's running now\n";
     else
         echo -e "- mcc daemon is already running\n";
     fi;
 };
-
-## repeatedly used in 'charge()'
-
-test_switch() { if eval $test; then switch_ $turn_1; fi; };
-
-## performs some post-'charge(test_valid)' actions
-
-charge_acts() {
-    if $(auto_switch); then set_prop auto_switch false; overridden=true; fi;
-    test_switch;
-};
-
-## tests and updates up, down_threshold
 
 test_boundaries() {
     if [[ ! -z $2 ]]; then
@@ -212,27 +203,11 @@ test_boundaries() {
         fi;
     fi;
     if [[ $boundary_err && ! $force ]]; then
-        abort 'Please give a level between 15 - 85';
+        abort 'Please give a level / levels between 15 - 85';
     fi;
     if [[ -z $u ]]; then u=$1; fi; set_prop up_threshold $u;
     if [[ -z $d ]]; then d=$2; fi; set_prop down_threshold $d;
     echo -e "- New values saved\n";
-};
-
-## tests whether the device is charging
-
-is_charging() { grep -q ^POWER_SUPPLY_STATUS=Charging$ $(uevent_f); };
-
-## tests whether the daemon is running
-
-is_runningd() {
-    ps | grep -v ' grep ' | grep ' root ' | grep ' {mcc} ' | grep -q ' --launch-daemon$';
-};
-
-## tests whether sysfs refs are set
-
-are_refs_set() {
-    test $(uevent_f) != dummy_Events && test $(get_prop switch_1) != dummy_Switch;
 };
 
 # Always get props in realtime
@@ -263,21 +238,16 @@ set_ctrl_refs() {
     echo -e "- Attention :- Please make sure the device is charging\n";
     sleep 5;
     echo -e "- Re-configuring sysfs references...\n";
-
-    ## get all possible references
-    find /sys/devices /sys/module -type f -name uevent >$uevent_cache;
-
+    find -L /sys/class /sys/devices /sys/module -type f -name uevent >$uevent_cache;
     while read uevent; do
         chmod u+r $uevent;
 
         ## cycling through all, get a matching uevent file
-        if grep -q ^POWER_SUPPLY_NAME=.*batt.*$ $uevent && grep -q ^POWER_SUPPLY_STATUS=Charging$ $uevent; then
+        if grep -q ^POWER_SUPPLY_NAME=.*[Bb]att.*$ $uevent && grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $uevent; then
             set_prop uevent $uevent;
             i=1;
             for ref in ${uevent%/*}/*; do
                 if [[ -f $ref ]]; then
-
-                    ## [[ -w $ref ]] will always succeed ( --> root ), so use this
                     if ! ls -l $ref | awk '{ print $1 }' | grep -q w; then
                         continue;
                     fi;
@@ -287,45 +257,21 @@ set_ctrl_refs() {
 
                 ## cycling through all, get a possible boolean switch
                 case $(cat $ref) in
-                    1       )
-                        echo 0 >$ref;        c_ON=1;        c_OFF=0;
-                    ;;
-                    0       )
-                        echo 1 >$ref;        c_ON=0;        c_OFF=1;
-                    ;;
-                    on      )
-                        echo off >$ref;      c_ON=on;       c_OFF=off;
-                    ;;
-                    off     )
-                        echo on >$ref;       c_ON=off;      c_OFF=on;
-                    ;;
-                    true    )
-                        echo false >$ref;    c_ON=true;     c_OFF=false;
-                    ;;
-                    false   )
-                        echo true >$ref;     c_ON=false;    c_OFF=true;
-                    ;;
-                    enable  )
-                        echo disable >$ref;  c_ON=enable;   c_OFF=disable;
-                    ;;
-                    disable )
-                        echo enable >$ref;   c_ON=disable;  c_OFF=enable;
-                    ;;
-                    enabled )
-                        echo disabled >$ref; c_ON=enabled;  c_OFF=disabled;
-                    ;;
-                    disabled)
-                        echo enabled >$ref;  c_ON=disabled; c_OFF=enabled;
-                    ;;
-                    *       )
-                        continue;
-                    ;;
+                    1       ) c_ON=1;        c_OFF=0;        ;;
+                    0       ) c_ON=0;        c_OFF=1;        ;;
+                    on      ) c_ON=on;       c_OFF=off;      ;;
+                    off     ) c_ON=off;      c_OFF=on;       ;;
+                    true    ) c_ON=true;     c_OFF=false;    ;;
+                    false   ) c_ON=false;    c_OFF=true;     ;;
+                    enable  ) c_ON=enable;   c_OFF=disable;  ;;
+                    disable ) c_ON=disable;  c_OFF=enable;   ;;
+                    enabled ) c_ON=enabled;  c_OFF=disabled; ;;
+                    disabled) c_ON=disabled; c_OFF=enabled;  ;;
+                    *       ) continue;                      ;;
                 esac;
 
-                ## sleep for 100ms, needed for some bad kernels
-                usleep 100000;
-
-                ## test if that works correctly
+                ## test whether that works correctly
+                echo $c_OFF >$ref; usleep 100000;
                 if ! is_charging; then
                     echo $c_ON >$ref; usleep 100000;
                     if is_charging; then
@@ -345,29 +291,8 @@ set_ctrl_refs() {
         ## switch is not found, reset uevent and toggle daemon mode OFF
         set_prop uevent dummy_Events;
         if $(daemon_mode); then set_prop daemon_mode false; fi;
-        abort "Your device don't support these functionalities";
+        abort 'Your device does not support these functionalities';
     fi;
-
-    ## switch is found, yield success
-    echo -e "- Done\n";
-};
-
-# Function for resetting sysfs refs perms
-
-reset_perms() {
-    if are_refs_set; then
-        chmod u+r $(uevent_f) $(get_prop switch_1 | awk '{ print $1 }');
-        sec_switch=$(get_prop switch_2 | awk '{ print $1 }');
-        if [[ $sec_switch != dummy_Switch ]]; then chmod u+r $sec_switch; fi;
-    fi;
-};
-
-# Function for resetting battery stats
-
-reset_stats() {
-    echo -e "- Resetting battery statistics...\n";
-    dumpsys batterystats --reset >/dev/null;
-    if [[ $1 == rm ]]; then rm -f /data/system/batterystats.bin; fi;
     echo -e "- Done\n";
 };
 
@@ -377,14 +302,14 @@ charge() {
     turn_1=OFF; turn_2=ON; text=disabled; test='is_charging';
     if [[ $1 == enable ]]; then
         turn_1=ON; turn_2=OFF; text=enabled; test='! is_charging';
-        if reset_perms; is_charging; then switch_ OFF; fi;
+        reset_perms; if is_charging; then switch_ OFF; fi;
     fi;
     if [[ ! -z $2 ]]; then
         if echo $2 | grep -Eq ^[0-9]+%$; then
             level=${2%%%}; test_bound $level;
             charge_acts;
             echo -e "- Charging $text until $2...\n";
-            until [[ $(batt_level) -eq $level ]]; do
+            while [[ ! $(batt_level) -eq $level ]]; do
                 reset_perms; test_switch; usleep 100000;
             done;
         elif echo $2 | grep -Eq ^[0-9]+[smh]$; then
@@ -407,28 +332,23 @@ charge() {
     fi;
 };
 
-# Disable env logger
-set +x;
-
-# Logger
+# Switch logger to mod_dir
 if [[ ! $no_file_logs ]]; then
-    echo -e "mcc versionCode == 201802281" >$ver_log;
+    echo -e "mcc versionCode == 201803051" >$ver_log;
     echo -e "magisk versionCode == $(magisk -V)\n\n" >>$ver_log;
     echo -e "device properties\n" >>$ver_log;
     for prop in ro.product.brand ro.product.model ro.build.product ro.product.device ro.build.description ro.build.fingerprint ro.product.cpu.abi ro.product.cpu.abilist; do
         echo "$prop :- $(getprop $prop)" >>$ver_log;
     done;
     echo -e "\n\n" >>$ver_log;
-    set -x 2>>$ver_log;
+    set +x; set -x 2>>$ver_log;
 fi;
 
-# Handle [ --force ]
-if [[ $1 == --force ]]; then force=true; shift; fi;
-
 # Handle given arguments
+## see the README for what they do
+if [[ $1 == --force ]]; then force=true; shift; fi;
 case $1 in
 
-    ## some info about current status
     --info)
         test_refs; reset_perms;
         echo -e "- Battery status\n";
@@ -450,41 +370,34 @@ case $1 in
         echo -e "-- background daemon mode :- $status\n";
 
         status='Not running'; if is_runningd; then status=Running; fi;
-        echo -e "-- daemon ( bg_activity ) status :- $status\n";
+        echo -e "-- daemon ( bg-activity ) status :- $status\n";
     ;;
 
-    ## help page ( README.md without Changelog )
     --help) show_help;
     ;;
 
-    ## re-test and configure sysfs references
     --reconf) set_ctrl_refs;
     ;;
 
-    ## reset battery stats
     --rm-stats) reset_stats rm;
     ;;
 
-    ## call am to route to paypal donate page
     --donate)
         echo -e "- Heyyo!!! Thanks\n";
         sleep 2;
         am start https://paypal.me/JayminSuthar >/dev/null;
     ;;
 
-    ## toggle auto shut
     --auto-shut)
         if ! $(auto_shut) && $(daemon_mode); then test_refs; fi;
-        toggle auto_shut 'automatic power-off';
+        toggle auto_shut 'auto shut';
     ;;
 
-    ## toggle auto switch
     --auto-switch)
         if ! $(auto_switch) && $(daemon_mode); then test_refs; fi;
-        toggle auto_switch 'automatic switching';
+        toggle auto_switch 'auto switch';
     ;;
 
-    ## toggle daemon mode
     --daemon-mode)
         if ! $(daemon_mode); then
             if $(auto_shut) || $(auto_switch); then
@@ -493,19 +406,15 @@ case $1 in
                 abort 'Please toggle either of auto switch or auto shut ON first';
             fi;
         fi;
-        toggle daemon_mode 'background daemon mode';
+        toggle daemon_mode 'daemon mode';
     ;;
 
-    ## enable charging
-    ## ( either on demand or for certain % / TIME )
     --enable) test_refs; charge enable $2;
     ;;
 
-    ## disable charging
     --disable) test_refs; charge disable $2;
     ;;
 
-    ## fork the daemon unless running
     --re-daemon)
         if $(daemon_mode); then
             if $(auto_shut) || $(auto_switch); then
@@ -518,7 +427,6 @@ case $1 in
         fi;
     ;;
 
-    ## launch the daemon
     --launch-daemon)
         while $(auto_shut) || $(auto_switch) && $(daemon_mode); do
             if ! are_refs_set; then sleep 2; continue; fi;
@@ -550,14 +458,12 @@ case $1 in
         done;
     ;;
 
-    ## thresholds back to defaults
     --default)
         set_prop shut_threshold 20;
         set_prop up_threshold 80; set_prop down_threshold 70;
         echo -e "- Reverted all the thresholds to defaults\n";
     ;;
 
-    ## update auto shut threshold
     --shut)
         if [[ ! -z $2 ]]; then
             if echo $2 | grep -Eq ^[0-9]+$; then
@@ -577,7 +483,6 @@ case $1 in
         echo -e "- New value saved\n";
     ;;
 
-    ## update auto switch thresholds
     --switch)
         if [[ ! -z $3 ]]; then
             test_level $3; test_level $2;
@@ -586,7 +491,7 @@ case $1 in
             elif [[ $2 -gt $3 ]]; then
                 test_diff $2 $3; test_boundaries $2 $3;
             else
-                abort "Please don't give same values";
+                abort 'Please do not give same values';
             fi;
         elif [[ ! -z $2 ]]; then
             test_level $2; test_boundaries $2;
@@ -595,9 +500,8 @@ case $1 in
         fi;
     ;;
 
-    ## with no arguments, ask user to go to help
     *)
-        echo -e "- Heyyo fella, Invalid argument(s)\n";
+        echo -e "- Heyyo fella, invalid argument(s)\n";
         sleep 1;
         show_help;
     ;;
