Sync with my personal Repo

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,11 +1,11 @@
 #!/sbin/sh
-# MC's Charging Controller
-# mcc Installer (201804151)
-# MCMotherEffin' @ XDA Developers
+# My Charging Controller
+# mcc Install (201804151)
+# JayminSuthar @ xda-developers
 
 # Copyright (c) 2018 Jaymin Suthar. All rights reserved.
 
-# This file is a part of "MC's Charging Controller (mcc)".
+# This file is a part of "My Charging Controller (mcc)".
 
 # mcc is released under the terms of the GNU GPL v3, as been
 ## published by the Free Software Foundation. And permission
@@ -19,13 +19,13 @@
 # You should already have received a copy of GPLv3 with mcc,
 ## if not, see <http://www.gnu.org/licenses/>.
 
-if grep '^/sbin/sh' </proc/$$/cmdline >/dev/null; then
+if [ ! $BOOTMODE ]; then
     for line in ' ' 'mcc: error: mcc requires Magisk Manager installation' ' '; do
         echo -e "ui_print $line\nui_print" >>/proc/self/fd/$2;
     done;
     exit 1;
 elif ! util_funcs=$(ls /data/adb/magisk/util_functions.sh || ls /data/magisk/util_functions.sh) || test ! $(sed -n 's/^MAGISK_VER_CODE=//p' $util_funcs) -ge 1410; then
-    echo -e 'mcc: error: mcc requires Magisk >= 1410\n'; exit 1;
+    echo -e '\n\nmcc: error: mcc requires Magisk >= 1410\n'; exit 1;
 fi;
 set -x; echo -e '\n';
 zip_file="$3";
@@ -36,17 +36,15 @@ mod_dir=$merge_root/mcc;
 image=${util_funcs%/*/*}/magisk_merge.img;
 mount_point=$(find /sbin/.core/img /magisk -type d -maxdepth 0);
 main_mod_dir=$mount_point/mcc;
-lock_file=$main_mod_dir/lock;
 abort() { echo -e "mcc: error: $1\n"; exit 1; }
 printp() { echo -e "mcc: info: $1\n"; }
 get_prop() { sed -n "s/^$1=//p" $2; }
 set_prop() { sed -i "s|^$1=.*|$1=$2|g" $mod_dir/files/secure/mcc.conf; }
 is_charging() { grep -q '^POWER_SUPPLY_STATUS=[Cc]harging$' $uevent; }
-which_installed() { get_prop versionCode $main_mod_dir/module.prop || echo 0; }
-imgsize_test() {
+get_size() {
     e2fsck -n $image | grep -Eo '[0-9]+/[0-9]+ blocks' | awk -F/ "{ print int((\$$1 + 255) / 256) }";
 }
-set_perm_recursive() {
+set_perms() {
     find $1 | while read entry; do
         chown 0:$2 $entry;
         chmod $3 $entry; if [[ -d $entry ]]; then chmod 0755 $entry; fi;
@@ -55,19 +53,19 @@ set_perm_recursive() {
 }
 rm -rf $tmp_dir; mkdir -p $merge_root;
 echo -e '-------------------------------------------------------------\n';
-echo "                  MC's Charging Controller                      ";
+echo "                    MC's Charging Controller                      ";
 echo -e '-------------------------------------------------------------\n\n\n';
 printp 'Checking compatibility (requires charging ON)...'; sleep 3;
-find /sys/devices /sys/module -type f -name uevent >$tmp_file;
+find /sys/devices /sys/module -type f -name uevent | grep -E '[Bb]att|[Cc]harg' >$tmp_file;
 export no_ver_logs=true; (mcc --enable; sleep 2; mcc --clean) >/dev/null;
 i=1;
 while read uevent; do
     if grep -q '^POWER_SUPPLY_NAME=.*[Bb]att' $uevent && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $uevent; then
         while read eff_uevent; do
-            if (grep -Eq '^POWER_SUPPLY_NAME=.*([Bb]att|USB|usb)' $eff_uevent && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $eff_uevent) || grep -q '^DRIVER=.*[Cc]harger' $eff_uevent; then
+            if (grep -Eq '^POWER_SUPPLY_NAME=.*([Bb]att|USB|usb)' $eff_uevent && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $eff_uevent) || grep -Eq '^DRIVER=.*[Cc]harg(er|ing)' $eff_uevent; then
                 for ref in ${eff_uevent%/*}/*; do
                     if test -f $ref && ls -l $ref | grep -Eq '^[a-z\-]+w[a-z\-]* '; then
-                        case $(cat $ref) in
+                        case "$(cat $ref)" in
                             1       ) c_ON=1;        c_OFF=0;        ;;
                             0       ) c_ON=0;        c_OFF=1;        ;;
                             on      ) c_ON=on;       c_OFF=off;      ;;
@@ -101,8 +99,8 @@ printp OK; echo -e '\n';
 if [[ -f $image ]]; then
     printp "$image exists";
     e2fsck -pf $image >&2;
-    img_total=$(imgsize_test 2);
-    if [[ $(imgsize_test 1) -eq $img_total ]]; then
+    img_total=$(get_size 2);
+    if [[ $(get_size 1) -eq $img_total ]]; then
         printp "Expanding $image...";
         resize2fs $image $((img_total + 32))M;
     fi;
@@ -117,9 +115,7 @@ for minor in 1 2 3 4 5 6 7; do
     loop_device=/dev/block/loop$minor;
     if [[ ! -b $loop_device ]]; then mknod $loop_device b 7 $minor; fi;
     losetup $loop_device $image;
-    if mount -t ext4 -o rw,noatime $loop_device $merge_root; then
-        break;
-    fi;
+    if mount -t ext4 -o rw,noatime $loop_device $merge_root; then break; fi;
 done;
 if ! grep -q " $merge_root " /proc/mounts; then
     abort "Failed to mount $image";
@@ -135,9 +131,9 @@ fi;
 set_prop uevent $uevent;
 for i in 1 2; do
     switch="$(eval echo \$switch_$i)";
-    if [[ ! -z $switch ]]; then set_prop switch_$i "$switch"; fi;
+    if [[ ! -z "$switch" ]]; then set_prop switch_$i "$switch"; fi;
 done;
-if test $(which_installed) -ge 201804151 && old_conf=$(ls $main_mod_dir/files/secure/mcc.conf); then
+if test $(get_prop versionCode $main_mod_dir/module.prop || echo 0) -ge 201804151 && old_conf=$(ls $main_mod_dir/files/secure/mcc.conf); then
     printp 'Restoring configurations...';
     for prop in auto_shut auto_switch up_threshold down_threshold shut_threshold; do
         set_prop $prop $(get_prop $prop $old_conf);
@@ -146,8 +142,7 @@ fi;
 touch $mod_dir/auto_mount $main_mod_dir/update;
 cp -f $mod_dir/module.prop $main_mod_dir/;
 printp 'Setting permissions...';
-set_perm_recursive $mod_dir    0 0644;
-set_perm_recursive $bin_dir 2000 0755;
+set_perms $mod_dir 0 0644; set_perms $bin_dir 2000 0755;
 umount $merge_root; losetup -d $loop_device;
 rm -rf $tmp_dir;
 printp Done; echo -e '\n';
diff --git a/system/xbin/mcc b/system/xbin/mcc
--- a/system/xbin/mcc
+++ b/system/xbin/mcc
@@ -1,11 +1,11 @@
 #!/system/bin/sh
-# MC's Charging Controller
+# My Charging Controller
 # mcc Main (201804151)
-# MCMotherEffin' @ XDA Developers
+# JayminSuthar @ xda-developers
 
 # Copyright (c) 2018 Jaymin Suthar. All rights reserved.
 
-# This file is a part of "MC's Charging Controller (mcc)".
+# This file is a part of "My Charging Controller (mcc)".
 
 # mcc is released under the terms of the GNU GPL v3, as been
 ## published by the Free Software Foundation. And permission
@@ -38,26 +38,24 @@ export PATH=$mod_dir/busybox:$PATH;
 if (! busybox | grep 'topjohnwu ' || ! which awk) >/dev/null; then
     echo -e 'mcc: error: Failed to set BusyBox up\n'; exit;
 fi;
-abort() { echo -e "mcc: error: $1" >&2; echo -e "mcc: error: $1\n"; exit; }
+abort() { echo "mcc: error: $1" >&2; echo -e "mcc: error: $1\n"; exit; }
 printp() { echo -e "mcc: info: $1\n"; }
 warn() { echo -e "mcc: warning: $1\n"; }
-exit_help() { head -99 $mod_dir/docs/README.md; exit; }
+exxit_() { head -99 $mod_dir/docs/README.md; exit; }
 get_prop() { sed -n "s/^$1=//p" $2 $config; }
 set_prop() { sed -i "s|^$1=.*|$1=$2|g" $config; }
 get_cpid() {
     for pid in $(ps | awk "!/ awk / && / $1$/{ print \$1 }"); do
-        if [[ $(awk '/^PPid: /{ print $2 }' /proc/$pid/status) -eq $$ ]]; then
-            echo $pid; break;
-        fi;
-        unset pid;
+        case $(awk '/^PPid: /{ print $2 }' /proc/$pid/status) in
+            $$) echo $pid; break; ;;
+        esac;
     done;
 }
 is_charging() {
-    if [[ $1 == cur ]]; then
-        test $(get_prop POWER_SUPPLY_CURRENT_NOW $(uevent_f)) -le 0;
-    else
-        grep -q '^POWER_SUPPLY_STATUS=[Cc]harging$' $(uevent_f);
-    fi;
+    case $1 in
+        cur) test $(get_prop POWER_SUPPLY_CURRENT_NOW $(uevent_f)) -le 0; ;;
+        *  ) grep -q '^POWER_SUPPLY_STATUS=[Cc]harging$' $(uevent_f);     ;;
+    esac;
 }
 is_runningd() {
     ps | awk '!/ awk / && / root / && / {mcc} / && / --launch-daemon$/' | grep -vq "^ *$$ ";
@@ -109,10 +107,12 @@ charge_init() {
     if ps | awk '!/ awk / && / root / && / {mcc} / && / (--enable|-e|--disable|-d) ?[0-9smh%]*$' | grep -vq "^ *$$ "; then
         abort 'Another session is already running';
     fi;
-    set_prop superceded_yet 0; touch $lock_file;
+    if [[ ! -f $lock_file ]]; then touched=true; fi;
+    re_count; touch $lock_file;
     switch_ $turn_1;
 }
 charge_loop() { while eval $1; do switch_ $turn_1; sleep 1; done; }
+re_count() { set_prop superceded_yet 0; }
 write_() {
     for i in 1 2; do
         switch=$(get_prop switch_$i | awk '{ print $1 }');
@@ -131,10 +131,7 @@ switch_() {
     esac;
     for i in 1 2 3 4 5 6 7 8 9 10; do
         if eval $test; then
-            if [[ $(superceded_yet) -eq 10 ]]; then
-                set_prop superceded_yet 0;
-            fi;
-            break;
+            if [[ $(superceded_yet) -eq 10 ]]; then re_count; fi; break;
         elif [[ $(superceded_yet) -lt 10 ]]; then
             set_prop superceded_yet $(($(superceded_yet) + 1));
         else
@@ -159,16 +156,16 @@ uevent_f() { get_prop uevent; }
 set_ctrl_refs() {
     for i in 1 2; do set_prop switch_$i dummy_Switch; done;
     printp 'Reconfiguring internals (requires charging ON)...'; sleep 3;
-    find /sys/devices /sys/module -type f -name uevent >$uevents;
+    find /sys/devices /sys/module -type f -name uevent | grep -E '[Bb]att|[Cc]harg' >$uevents;
     i=1;
     while read uevent; do
         if grep -q '^POWER_SUPPLY_NAME=.*[Bb]att' $uevent && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $uevent; then
             set_prop uevent $uevent;
             while read eff_uevent; do
-                if (grep -Eq '^POWER_SUPPLY_NAME=.*([Bb]att|USB|usb)' $eff_uevent && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $eff_uevent) || grep -q '^DRIVER=.*[Cc]harger' $eff_uevent; then
+                if (grep -Eq '^POWER_SUPPLY_NAME=.*([Bb]att|USB|usb)' $eff_uevent && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $eff_uevent) || grep -Eq '^DRIVER=.*[Cc]harg(er|ing)' $eff_uevent; then
                     for ref in ${eff_uevent%/*}/*; do
                         if test -f $ref && ls -l $ref | grep -Eq '^[a-z\-]+w[a-z\-]* '; then
-                            case $(cat $ref) in
+                            case "$(cat $ref)" in
                                 1       ) c_ON=1;        c_OFF=0;        ;;
                                 0       ) c_ON=0;        c_OFF=1;        ;;
                                 on      ) c_ON=on;       c_OFF=off;      ;;
@@ -205,7 +202,7 @@ set_ctrl_refs() {
     fi;
     printp Done;
 }
-charge() {
+c_session() {
     case $1 in
         enable ) turn_1=ON;  turn_2=OFF; text=enabled;  ;;
         disable) turn_1=OFF; turn_2=ON;  text=disabled; ;;
@@ -226,7 +223,7 @@ charge() {
         else
             abort 'Invalid argument format';
         fi;
-        set_prop superceded_yet 0; rm -f $lock_file;
+        re_count; if [[ $touched ]]; then rm -f $lock_file; fi;
         switch_ $turn_2;
         printp 'Session ended';
     else
@@ -276,8 +273,8 @@ case $1 in
         if ! $(auto_switch); then test_refs; fi;
         toggle auto_switch 'Auto switch';
     ;;
-    -e|--enable)  test_refs; charge enable $2;  ;;
-    -d|--disable) test_refs; charge disable $2; ;;
+    -e|--enable ) test_refs; c_session enable  $2; ;;
+    -d|--disable) test_refs; c_session disable $2; ;;
     -rd|--re-daemon)
         if ! $(auto_shut) && ! $(auto_switch); then
             abort 'Neither auto switch or auto shut is ON';
@@ -315,8 +312,8 @@ case $1 in
     ;;
     -c|--clean)
         kill $(ps | awk "!/ awk / && / {mcc} / && !/^ *$$ /{ print \$1 }" | tr '\n' ' ');
-        set_prop superceded_yet 0;
-        rm -f $files_dir/* $mod_dir/lock;
+        re_count;
+        rm -f $files_dir/* $lock_file;
         printp 'Everything cleaned up';
     ;;
     -rc|--reset-cfg) set_ctrl_refs; ;;
@@ -334,14 +331,14 @@ case $1 in
         status=OFF; if $(auto_switch); then status=ON; fi;
         echo "-- automatic switching: $status";
         status=OFF; if $(auto_shut); then status=ON; fi;
-        echo "-- automatic power-off: $status\n";
+        echo -e "-- automatic power-off: $status\n";
         status='Not running'; if is_runningd; then status=Running; fi;
         echo -e "- Daemon status: $status\n";
     ;;
-    -h|--help) exit_help; ;;
+    -h|--help) exxit_; ;;
     *)
         warn 'Invalid argument(s)'; sleep 2;
-        exit_help;
+        exxit_;
     ;;
 esac;
 ) 2>$err_log) &);
