Release code 201803111

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,6 +1,6 @@
 #!/sbin/sh
 # MC's Charging Controller
-# mcc Installer ( 201803081 )
+# mcc Installer ( 201803111 )
 # MCMotherEffin' @ XDA Developers
 
 # Copyright (c) 2018 Jaymin " MCMotherEffin' " Suthar. All rights reserved.
@@ -15,43 +15,35 @@
 
 # Given the above rights, you are required to inform me
 ## if you re-distribute it ( wherever you do, it is public )
-## you should do so by sending me a Private Message at xda-developers.com
+## You should do so by sending me a Private Message at xda-developers.com
 
 # Finally, you should obtain a copy of the GNU GPL v3 from <http://gnu.org/licenses/>
 
-# Abort for this cases
+# Pre-exec operations
 if grep '^/sbin/sh' </proc/$$/cmdline >/dev/null; then
-    fd=/proc/self/fd/$2;
-
-    ui_print() { echo -e "ui_print $1\nui_print" >>$fd; };
-
-    ui_print ' ';  ui_print ' ';
-    ui_print '- Abort :- Please install in boot mode';
-    ui_print ' ';  ui_print ' ';
+    for message in ' ' ' ' '- Abort :- Please install in boot mode' ' ' ' '; do
+        echo -e "ui_print $message\nui_print" >>/proc/self/fd/$2;
+    done;
     exit 1;
-elif [ $(magisk -V;) -lt 1400 ]; then
-    echo -e "\n\nAbort :- Please install Magisk >= 1400\n"; exit 1;
+elif [ $(magisk -V) -lt 1410 ]; then
+    echo ' '; echo ' ';
+    echo -e "Abort :- Please install Magisk >= 1410\n"; exit 1;
+else
+    echo ' '; echo ' ';
 fi;
-echo -e "\n\n";
-
-# Define universal functionals
-zip_file="$3";
-
-abort() { echo -e "- Abort :- $1\n"; exit 1; };
 
 # Find BusyBox, Magisk mountpoint and set BusyBox applets up
-system=/system; if [ -d /system_root ]; then system=/system_root/system; fi;
-for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$;); do
+for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$); do
     if $magisk_bb | grep 'topjohnwu ' >/dev/null; then
-        image=${magisk_bb%/*/*}/magisk.img;
-        if [ -f $image ]; then
+        if image=$(ls ${magisk_bb%/*/*}/magisk.img); then
             for loop_device in /dev/block/loop*; do
                 if $magisk_bb losetup $loop_device | grep " $image$" >/dev/null; then
-                    for real_mount_point in $(grep "^$loop_device " /proc/mounts | $magisk_bb awk '{ print $2 }' | grep -Ev "^$system|^/vendor";); do
-                        if grep ^com.google.android.gms.unstable$ $real_mount_point/.core/hidelist >/dev/null; then
+                    for real_mount_point in $(grep "^$loop_device " /proc/mounts | $magisk_bb awk '{ print $2 }' | grep -Ev '^/system|^/vendor'); do
+                        if grep ^com.google.android.gms.unstable$ $real_mount_point/.core/hidelist >/dev/null && [ -d $real_mount_point/lost+found ] && [ -d $real_mount_point/.core/service.d ]; then
                             break 3;
+                        else
+                            unset real_mount_point;
                         fi;
-                        unset real_mount_point;
                     done;
                 fi;
             done;
@@ -59,16 +51,50 @@ for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$;); d
     fi;
     unset magisk_bb;
 done;
-if [ -z $magisk_bb -o -z $real_mount_point ]; then
-    abort 'Could not set environment based on Magisk';
-fi;
 tmp_dir=/dev/mcc_tmp;
 tmp_bin=$tmp_dir/busybox;
 rm -rf $tmp_bin; mkdir -p $tmp_bin;
 $magisk_bb --install -s $tmp_bin/;
 export PATH=$tmp_bin:$PATH;
+if [ -z $magisk_bb ] || [ -z $real_mount_point ] || [ "$(which awk)" != $tmp_bin/awk ]; then
+    echo -e "- Abort :- Could not set environment based on Magisk\n"; exit 1;
+fi;
 
-# Print module banner
+# Define variables
+## for tmp_dir, image, and real_mount_point, see the above
+zip_file="$3";
+tmp_file=$tmp_dir/cached;
+image=${image%/*}/magisk_merge.img;
+mount_point=/dev/mcc_img;
+mod_dir=$mount_point/mcc;
+inst_mod_dir=$real_mount_point/mcc;
+
+# Define functions
+## they are hardcoded as per the Installer's needs
+
+abort() { echo -e "- Abort :- $1\n"; exit 1; }
+
+is_charging() { grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $uevent; }
+
+get_prop() { sed -n s/^$1=//p $2; }
+
+set_prop() { sed -i "s|^$1=.*|$1=$2|g" $mod_dir/mcc.conf; }
+
+which_installed() { get_prop versionCode $inst_mod_dir/module.prop || echo 0; }
+
+imgsize_test() {
+    e2fsck -n $image | grep -Eo '[0-9]+/[0-9]+ blocks' | cut -d/ -f$1 | awk '{ print int(($1 + 255) / 256) }';
+}
+
+set_perm_recursive() {
+    find $1 | while read entry; do
+        chown 0:$2 $entry;
+        chcon u:object_r:system_file:s0 $entry;
+        if [[ ! -d $entry ]]; then chmod $3 $entry; else chmod 0755 $entry; fi;
+    done;
+}
+
+# Print the module banner
 echo -e "------------------------------------------------\n";
 echo -e "     MC's Charging Controller\n";
 echo -e "         by MCMotherEffin' @ XDA Developers\n";
@@ -79,11 +105,7 @@ echo -e "------------------------------------------------\n\n\n";
 echo -e "- Please make sure the device is charging\n";
 sleep 5;
 echo -e "- Checking compatibility...\n";
-tmp_file=$tmp_dir/cached;
 find /sys/devices /sys/module -type f -name uevent >$tmp_file;
-
-is_charging() { grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $uevent; };
-
 while read uevent; do
     chmod u+r $uevent;
     if grep -q ^POWER_SUPPLY_NAME=.*[Bb]att.*$ $uevent && is_charging; then
@@ -92,11 +114,13 @@ while read uevent; do
             if [[ -f $ref ]]; then
                 if ! ls -l $ref | awk '{ print $1 }' | grep -q w; then
                     continue;
+                else
+                    chmod u+r $ref;
                 fi;
             else
                 continue;
-            fi; chmod u+r $ref;
-            case $(cat $ref;) in
+            fi;
+            case $(cat $ref) in
                 1       ) c_ON=1;        c_OFF=0;        ;;
                 0       ) c_ON=0;        c_OFF=1;        ;;
                 on      ) c_ON=on;       c_OFF=off;      ;;
@@ -109,10 +133,9 @@ while read uevent; do
                 disabled) c_ON=disabled; c_OFF=enabled;  ;;
                 *       ) continue;                      ;;
             esac;
-            echo $c_OFF >$ref; sleep 0.2;
+            echo $c_OFF >$ref; sleep 0.3;
             if ! is_charging; then
-                dumpsys batterystats --reset >/dev/null;
-                echo $c_ON >$ref; sleep 0.2;
+                echo $c_ON >$ref; sleep 0.3;
                 if is_charging; then
                     eval switches_$i=\"$ref $c_ON $c_OFF\"; let i++;
                     if [[ $i -eq 3 ]]; then break 2; fi;
@@ -124,22 +147,17 @@ while read uevent; do
     fi;
 done <$tmp_file;
 if [[ $i -eq 1 ]]; then
-    abort 'Your device does not support these functionalities';
+    abort 'Could not succeed the compatibility check';
+else
+    echo -e "- OK\n\n\n";
 fi;
-echo -e "- OK\n\n\n";
 
 # Get image ready and mounted for un-installation
-image=${image%/*}/magisk_merge.img;
 if [[ -f $image ]]; then
     echo -e "- $image exists\n";
-
-    imgsize_test() {
-        e2fsck -n $image | grep -Eo '[0-9]+/[0-9]+ blocks' | cut -d/ -f$1 | awk '{ print int(($1 + 255) / 256) }';
-    };
-
     e2fsck -pf $image >&2;
-    img_total=$(imgsize_test 2;);
-    if [[ $(imgsize_test 1;) -eq $img_total ]]; then
+    img_total=$(imgsize_test 2);
+    if [[ $(imgsize_test 1) -eq $img_total ]]; then
         echo -e "- Expanding $image...\n";
         resize2fs $image $((img_total + 32))M;
     fi;
@@ -148,36 +166,29 @@ else
     make_ext4fs -l 64M $image >&2;
 fi;
 echo -e "- Mounting $image...\n";
-mount_point=/dev/mcc_img;
 mkdir $mount_point;
-
-is_mounted() { grep -q " $mount_point " /proc/mounts; };
-
-for minor in $(seq -s ' ' 7;); do
+for minor in $(seq -s ' ' 7); do
     loop_device=/dev/block/loop$minor;
     if [[ ! -b $loop_device ]]; then mknod $loop_device b 7 $minor; fi;
     if losetup $loop_device $image; then
-        mount -t ext4 -o rw,noatime $loop_device $mount_point;
+        if mount -t ext4 -o rw,noatime $loop_device $mount_point; then
+            break;
+        fi;
     fi;
-    if is_mounted; then break; fi;
 done;
-if ! is_mounted; then abort "Could not mount $image"; fi;
+if ! grep -q " $mount_point " /proc/mounts; then
+    abort "Could not mount $image";
+fi;
 
-# Proceed
-mod_dir=$mount_point/mcc; inst_mod_dir=$real_mount_point/mcc;
-
-get_prop() { sed -n s/^$1=//p $2; };
-
-which_installed() { get_prop versionCode $inst_mod_dir/module.prop || echo 0; };
-
-if [[ $(get_prop versionCode $mod_dir/module.prop || which_installed;) -ge 201803081 ]]; then
+# Proceed to un-installation
+if [[ $(get_prop versionCode $mod_dir/module.prop || which_installed) -ge 201803111 ]]; then
 
     # Uninstall
     echo -e "- Same or newer already installed\n";
     echo -e "- Attention :- Cleaning installation...\n";
     rm -rf $mod_dir $inst_mod_dir /cache/mcc_e*.log;
-    kill $(ps | grep -v ' grep ' | grep ' {mcc} ' | awk '{ print $1 }' | tr '\n' ' ';);
-    if inst_mcc=$(ls $system/xbin/mcc || ls $system/bin/mcc;) && [[ $(magisk -V;) -ge 1410 ]]; then
+    kill $(ps | grep -v ' grep ' | grep ' {mcc} ' | awk '{ print $1 }' | tr '\n' ' ');
+    if inst_mcc=$(ls /system/xbin/mcc || ls /system/bin/mcc); then
         umount $inst_mcc; rm -f $inst_mcc; umount ${inst_mcc%/*};
     fi;
 else
@@ -188,21 +199,18 @@ else
     unzip -o "$zip_file" 'system/*' mcc.conf service.sh module.prop -d $mod_dir >&2;
     unzip -o "$zip_file" README.md -d $mod_dir/docs >&2;
     bin_dir=$mod_dir/system/xbin;
-    if [[ ! -d $system/xbin ]]; then
+    if [[ ! -d /system/xbin ]]; then
         mv $bin_dir $mod_dir/system/bin; bin_dir=$mod_dir/system/bin;
     fi;
-
-    set_prop() { sed -i "s|^$1=.*|$1=$2|g" $mod_dir/mcc.conf; };
-
-    if [[ $(which_installed) -ge 201802251 ]] && old_conf=$(ls $inst_mod_dir/mcc.conf;); then
+    if [[ $(which_installed) -ge 201802251 ]] && old_conf=$(ls $inst_mod_dir/mcc.conf); then
         echo -e "- Restoring configurations...\n";
         for prop in auto_shut auto_switch daemon_mode up_threshold down_threshold shut_threshold; do
-            set_prop $prop $(get_prop $prop $old_conf;);
+            set_prop $prop $(get_prop $prop $old_conf);
         done;
     fi;
     set_prop uevent $uevent;
     for i in 1 2; do
-        switch="$(eval echo \$switch_$i;)";
+        switch="$(eval echo \$switch_$i)";
         case $switch in
             '') break;                        ;;
             * ) set_prop switch_$i "$switch"; ;;
@@ -212,19 +220,6 @@ else
     mkdir $inst_mod_dir;
     touch $inst_mod_dir/update;
     cp -f $mod_dir/module.prop $inst_mod_dir;
-
-    set_perm_recursive() {
-        find $1 | while read entry; do
-            chown 0:$2 $entry;
-            if [[ ! -d $entry ]]; then
-                chmod $3 $entry;
-            else
-                chmod 0755 $entry;
-            fi;
-            chcon u:object_r:system_file:s0 $entry;
-        done;
-    };
-
     echo -e "- Setting permissions...\n";
     set_perm_recursive $mod_dir    0 0644;
     set_perm_recursive $bin_dir 2000 0755;
diff --git a/system/xbin/mcc b/system/xbin/mcc
--- a/system/xbin/mcc
+++ b/system/xbin/mcc
@@ -1,6 +1,6 @@
 #!/system/bin/sh
 # MC's Charging Controller
-# mcc Main ( 201803081 )
+# mcc Main ( 201803111 )
 # MCMotherEffin' @ XDA Developers
 
 # Copyright (c) 2018 Jaymin " MCMotherEffin' " Suthar. All rights reserved.
@@ -15,34 +15,35 @@
 
 # Given the above rights, you are required to inform me
 ## if you re-distribute it ( wherever you do, it is public )
-## you should do so by sending me a Private Message at xda-developers.com
+## You should do so by sending me a Private Message at xda-developers.com
 
 # Finally, you should obtain a copy of the GNU GPL v3 from <http://gnu.org/licenses/>
 
 # Pre-exec operations
-if ! id | grep uid=0 >/dev/null; then
+if ! id | grep ^uid=0 >/dev/null; then
     su -c mcc "$@"; exit $?;
 elif [ ! $no_file_logs ]; then
     if [ ! $no_err_logs ]; then
         no_err_logs=true mcc "$@" 2>/cache/mcc_err.log; exit $?;
+    else
+        set -x 2>/cache/mcc_env.log;
     fi;
-    set -x 2>/cache/mcc_env.log;
+else
+    echo ' ';
 fi;
-echo ' ';
 
 # Find BusyBox, Magisk mountpoint and set BusyBox applets up
-system=/system; if [ -d /system_root ]; then system+=_root/system; fi;
-for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$;); do
+for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$); do
     if $magisk_bb | grep 'topjohnwu ' >/dev/null; then
-        image=${magisk_bb%/*/*}/magisk.img;
-        if [ -f $image ]; then
+        if image=$(ls ${magisk_bb%/*/*}/magisk.img); then
             for loop_device in /dev/block/loop*; do
                 if $magisk_bb losetup $loop_device | grep " $image$" >/dev/null; then
-                    for mount_point in $(grep "^$loop_device " /proc/mounts | $magisk_bb awk '{ print $2 }' | grep -Ev "^$system|^/vendor";); do
-                        if grep ^com.google.android.gms.unstable$ $mount_point/.core/hidelist >/dev/null; then
+                    for mount_point in $(grep "^$loop_device " /proc/mounts | $magisk_bb awk '{ print $2 }' | grep -Ev '^/system|^/vendor'); do
+                        if grep ^com.google.android.gms.unstable$ $mount_point/.core/hidelist >/dev/null && [ -d $mount_point/lost+found ] && [ -d $mount_point/.core/service.d ]; then
                             break 3;
+                        else
+                            unset mount_point;
                         fi;
-                        unset mount_point;
                     done;
                 fi;
             done;
@@ -50,41 +51,80 @@ for magisk_bb in $(find /data -type f -name busybox | grep /magisk/busybox$;); d
     fi;
     unset magisk_bb;
 done;
-if [ -z $magisk_bb -o -z $mount_point ]; then
-    echo -e "- Abort :- Could not set environment based on Magisk\n"; exit 1;
-fi;
 mod_dir=$mount_point/mcc;
 mcc_bin=$mod_dir/busybox;
 rm -rf $mcc_bin; mkdir $mcc_bin;
 $magisk_bb --install -s $mcc_bin/;
 export PATH=$mcc_bin:$PATH;
+if [ -z $magisk_bb ] || [ -z $mount_point ] || [ $(which awk) != $mcc_bin/awk ]; then
+    echo -e "- Abort :- Could not set environment based on Magisk\n"; exit 1;
+fi;
 
-# Define universal functionals ( not all )
-cache_dir=$mod_dir/cache;
+# Define variables
+## for mod_dir, see the above
 config=$mod_dir/mcc.conf;
+cache_dir=$mod_dir/cache;
 ver_log=$cache_dir/verbose.log;
+uevent_cache=$cache_dir/uevent_cache.tmp;
+
+# Define functions
+## they are hardcoded as per the Main's needs
 
 abort() {
-    echo -e "\n- Fatal error --> '$1'" >>/cache/mcc_err.log;
+    echo ' ' >>/cache/mcc_err.log;
+    echo "- Aborting to the argument --> '$1'" >>/cache/mcc_err.log;
     echo -e "- Abort :- $1\n";
     exit 1;
-};
+}
+
+exit_help() {
+    while IFS= read line; do
+        case $line in
+            '### Release notes') break;        ;;
+            *                  ) echo "$line"; ;;
+        esac;
+    done <$mod_dir/docs/README.md;
+    exit 1;
+}
 
 get_prop() {
-    prop_file=$config; if [[ ! -z $2 ]]; then prop_file=$2; fi;
-    sed -n s/^$1=//p $prop_file;
-};
+    if [[ ! -z $2 ]]; then prop_file=$2; else prop_file=$config; fi;
+    if ! sed -n s/^$1=//p $prop_file; then
+        abort "Could not find file '$prop_file'";
+    fi;
+}
 
 set_prop() {
-    prop_file=$config; if [[ ! -z $3 ]]; then prop_file=$3; fi;
-    sed -i "s|^$1=.*|$1=$2|g" $prop_file;
-};
+    if ! sed -i "s|^$1=.*|$1=$2|g" $config; then
+        abort "Could not find file '$config'";
+    fi;
+}
+
+get_cpid() { ## this is defined here cause it possibly is gonna be used in later versions
+    for pid in $(ps | grep -v ' grep ' | grep " $1$" | awk '{ print $1 }'); do
+        if [[ $(grep '^PPid: ' /proc/$pid/status | awk '{ print $2 }') -eq $$ ]]; then
+            echo $pid; break;
+        else
+            unset pid;
+        fi;
+    done;
+}
+
+is_charging() { grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $(uevent_f); }
+
+is_runningd() {
+    ps | grep -v ' grep ' | grep ' root ' | grep ' {mcc} ' | grep -q ' --launch-daemon$';
+}
+
+are_refs_set() {
+    test $(uevent_f) != dummy_Events && test $(get_prop switch_1 | awk '{ print $1 }') != dummy_Switch;
+}
 
 test_bound() {
     if [[ $1 -le 0 || $1 -ge 100 ]]; then
         abort 'Please give a level between 0 - 100';
     fi;
-};
+}
 
 test_level() {
     if echo $1 | grep -Eq ^[0-9]+$; then
@@ -92,95 +132,32 @@ test_level() {
     else
         abort 'Please give only numbers';
     fi;
-};
+}
 
 test_diff() {
     if [[ ! $1 -ge $(($2 + 5)) && ! $force ]]; then
-        abort "Please do not give this close thresholds";
+        abort 'Please do not give this close thresholds';
     fi;
-};
+}
 
-test_switch() { if eval $test; then switch_ $turn_1; fi; };
-
-charge_acts() {
-    if $(auto_switch); then set_prop auto_switch false; overridden=true; fi;
-    test_switch;
-};
-
-is_charging() { grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $(uevent_f); };
-
-is_runningd() {
-    ps | grep -v ' grep ' | grep ' root ' | grep ' {mcc} ' | grep -q ' --launch-daemon$';
-};
-
-are_refs_set() {
-    test $(uevent_f) != dummy_Events && test $(get_prop switch_1;) != dummy_Switch;
-};
-
-reset_perms() {
-    if are_refs_set; then
-        chmod u+r $(uevent_f) $(get_prop switch_1 | awk '{ print $1 }';);
-        sec_switch=$(get_prop switch_2 | awk '{ print $1 }';);
-        if [[ $sec_switch != dummy_Switch ]]; then chmod u+r $sec_switch; fi;
-    fi;
-};
-
-reset_stats() {
-    echo -e "- Resetting battery statistics...\n";
-    dumpsys batterystats --reset >/dev/null;
-    if [[ $1 == rm ]]; then rm -f /data/system/batterystats.bin; fi;
-    echo -e "- Done\n";
-};
-
-toggle() {
-    value=true; status=ON; if $($1); then value=false; status=OFF; fi;
-    echo -e "- Toggling $2 $status...\n";
-    set_prop $1 $value;
-    echo -e "- Done\n";
-};
-
-show_help() {
-    while IFS= read line; do
-        case $line in
-            "### What's new") break;        ;;
-            *               ) echo "$line"; ;;
-        esac;
-    done <$mod_dir/docs/README.md;
-    exit 1;
-};
-
-switch_() {
-    for i in 1 2; do
-        switch=$(get_prop switch_$i | awk '{ print $1 }';);
-        if [[ $switch == dummy_Switch ]]; then break; fi;
-        case $1 in
-            ON )
-                get_prop switch_$i | awk '{ print $2 }' >$switch;
-            ;;
-            OFF)
-                get_prop switch_$i | awk '{ print $3 }' >$switch;
-                reset_stats >/dev/null;
-            ;;
-        esac;
-    done;
-};
+test_switch() { if eval $test; then switch_ $turn_1; fi; }
 
 test_refs() {
     if ! are_refs_set; then
         echo -e "Attention :- No references set\n";
         set_ctrl_refs;
     fi;
-};
+}
 
 test_daemon() {
     if ! is_runningd; then
         echo -e "- mcc daemon is not running, launching it...\n";
         (no_file_logs=true mcc --launch-daemon </dev/null >/dev/null 2>&1 &);
-        echo -e "- It's running now\n";
+        echo -e "- It is running now\n";
     else
         echo -e "- mcc daemon is already running\n";
     fi;
-};
+}
 
 test_boundaries() {
     if [[ ! -z $2 ]]; then
@@ -192,46 +169,93 @@ test_boundaries() {
         if [[ $1 -gt 25 ]]; then
             d=$(($1 - 10));
         else
-            d=15;
             if [[ $1 -lt 20 ]]; then
-                d=$(($1 - 5));
-                if [[ $d -le 0 ]]; then
-                    d=1;
-                    if [[ $1 -eq 1 ]]; then u=2; fi;
+                if [[ $1 -lt 6 ]]; then
+                    if [[ $1 -eq 1 ]]; then u=2; d=1; else d=1; fi;
+                else
+                    d=$(($1 - 5));
                 fi;
+            else
+                d=15;
             fi;
         fi;
     fi;
-    if [[ $boundary_err && ! $force ]]; then
-        abort 'Please give a level / levels between 15 - 85';
+    if [[ ! $boundary_err || $force ]]; then
+        if [[ -z $u ]]; then u=$1; fi; set_prop up_threshold $u;
+        if [[ -z $d ]]; then d=$2; fi; set_prop down_threshold $d;
+        echo -e "- New values saved\n";
+    else
+        abort 'Please give a level between 15 - 85';
     fi;
-    if [[ -z $u ]]; then u=$1; fi; set_prop up_threshold $u;
-    if [[ -z $d ]]; then d=$2; fi; set_prop down_threshold $d;
-    echo -e "- New values saved\n";
-};
+}
+
+reset_perms() {
+    if are_refs_set; then
+        chmod u+r $(uevent_f) $(get_prop switch_1 | awk '{ print $1 }');
+        sec_switch=$(get_prop switch_2 | awk '{ print $1 }');
+        if [[ $sec_switch != dummy_Switch ]]; then chmod u+r $sec_switch; fi;
+    fi;
+}
+
+reset_stats() {
+    echo -e "- Resetting battery statistics...\n";
+    if [[ $(dumpsys batterystats --reset) != 'Battery stats reset.' ]]; then
+        echo "- Attention :- dumpsys possibly failed to reset stats\n";
+    fi;
+    if [[ $1 == rm ]]; then rm -f /data/system/batterystats.bin; fi;
+    echo -e "- Done\n";
+}
+
+charge_acts() {
+    if $(auto_switch); then set_prop auto_switch false; overridden=true; fi;
+    test_switch;
+}
+
+switch_() {
+    for i in 1 2; do
+        switch=$(get_prop switch_$i | awk '{ print $1 }');
+        if [[ $switch == dummy_Switch ]]; then break; fi;
+        case $1 in
+            ON )
+                get_prop switch_$i | awk '{ print $2 }' >$switch;
+            ;;
+            OFF)
+                get_prop switch_$i | awk '{ print $3 }' >$switch;
+                reset_stats >/dev/null;
+            ;;
+        esac;
+    done;
+}
+
+toggle() {
+    if $($1); then value=false; status=OFF; else value=true; status=ON; fi;
+    echo -e "- Toggling $2 $status...\n";
+    set_prop $1 $value;
+    echo -e "- Done\n";
+}
 
 # Always get props in realtime
 
-uevent_f() { get_prop uevent; };
+uevent_f() { get_prop uevent; }
 
-auto_shut() { get_prop auto_shut; };
+auto_shut() { get_prop auto_shut; }
 
-auto_switch() { get_prop auto_switch; };
+auto_switch() { get_prop auto_switch; }
 
-daemon_mode() { get_prop daemon_mode; };
+daemon_mode() { get_prop daemon_mode; }
 
-up_threshold() { get_prop up_threshold; };
+up_threshold() { get_prop up_threshold; }
 
-down_threshold() { get_prop down_threshold; };
+down_threshold() { get_prop down_threshold; }
 
-shut_threshold() { get_prop shut_threshold; };
+shut_threshold() { get_prop shut_threshold; }
 
-batt_level() { get_prop POWER_SUPPLY_CAPACITY $(uevent_f); };
+batt_level() { get_prop POWER_SUPPLY_CAPACITY $(uevent_f); }
 
-# This tests compatibility and sets references ( assumes device is charging )
+# Function for resetting sysfs references ( device must be charging )
+## it is the core of this entire project, so is completely documented
 
 set_ctrl_refs() {
-    uevent_cache=$cache_dir/uevent_cache.tmp;
 
     ## reset previous switches
     for i in 1 2; do set_prop switch_$i dummy_Switch; done;
@@ -253,13 +277,15 @@ set_ctrl_refs() {
                 if [[ -f $ref ]]; then
                     if ! ls -l $ref | awk '{ print $1 }' | grep -q w; then
                         continue;
+                    else
+                        chmod u+r $ref;
                     fi;
                 else
                     continue;
-                fi; chmod u+r $ref;
+                fi;
 
                 ## cycling through all, get a possible boolean switch
-                case $(cat $ref;) in
+                case $(cat $ref) in
                     1       ) c_ON=1;        c_OFF=0;        ;;
                     0       ) c_ON=0;        c_OFF=1;        ;;
                     on      ) c_ON=on;       c_OFF=off;      ;;
@@ -274,10 +300,9 @@ set_ctrl_refs() {
                 esac;
 
                 ## test whether that works correctly
-                echo $c_OFF >$ref; sleep 0.2;
+                echo $c_OFF >$ref; sleep 0.3;
                 if ! is_charging; then
-                    reset_stats >/dev/null;
-                    echo $c_ON >$ref; sleep 0.2;
+                    echo $c_ON >$ref; sleep 0.3;
                     if is_charging; then
 
                         ## yes it does, add it to mcc.conf
@@ -295,38 +320,46 @@ set_ctrl_refs() {
         ## switch is not found, reset uevent and toggle daemon mode OFF
         set_prop uevent dummy_Events;
         if $(daemon_mode); then set_prop daemon_mode false; fi;
-        abort 'Your device does not support these functionalities';
+        abort 'Could not set references';
+    else
+        echo -e "- Done\n";
     fi;
-    echo -e "- Done\n";
-};
+}
 
 # Function for [ -e / --enable / -d / --disable ] [ % / TIME ]
 
 charge() {
-    turn_1=OFF; turn_2=ON; text=disabled; test='is_charging';
-    if [[ $1 == enable ]]; then
-        turn_1=ON; turn_2=OFF; text=enabled; test='! is_charging';
-        reset_perms; if is_charging; then switch_ OFF; fi;
-    fi;
+    case $1 in
+        enable )
+            turn_1=ON; turn_2=OFF; text=enabled; test='! is_charging';
+            reset_perms; if is_charging; then switch_ OFF; fi;
+        ;;
+        disable)
+            turn_1=OFF; turn_2=ON; text=disabled; test='is_charging';
+        ;;
+    esac;
     if [[ ! -z $2 ]]; then
         if echo $2 | grep -Eq ^[0-9]+%$; then
-            level=${2%%%}; test_bound $level;
+            level=$(echo $2 | tr -d %);
+            test_bound $level;
+            switch_ $turn_2;
             charge_acts;
             echo -e "- Charging $text until $2...\n";
             while [[ ! $(batt_level) -eq $level ]]; do
                 reset_perms; test_switch; sleep 1;
             done;
+            switch_ $turn_2;
         elif echo $2 | grep -Eq ^[0-9]+[smh]$; then
             charge_acts;
             echo -e "- Charging $text for $2...\n";
             setsid sleep $2;
-            while ps | grep -v ' grep ' | grep -q " sleep $2$"; do
+            sleep_pid=$(get_cpid "sleep $2");
+            while ps | grep -q "^$sleep_pid "; do
                 reset_perms; test_switch; sleep 1;
             done;
         else
             abort 'Please give a valid argument';
         fi;
-        switch_ $turn_2;
     else
         charge_acts;
         echo -e "- Charging $text\n";
@@ -334,22 +367,21 @@ charge() {
     if [[ $overridden ]]; then
         set_prop auto_switch true; test_daemon >/dev/null;
     fi;
-};
+}
 
 # Switch logger to mod_dir
 if [[ ! $no_file_logs ]]; then
-    echo -e "mcc versionCode == 201803081" >$ver_log;
-    echo -e "magisk versionCode == $(magisk -V;)\n\n" >>$ver_log;
+    echo -e 'mcc versionCode == 201803111' >$ver_log;
+    echo -e "magisk versionCode == $(magisk -V)\n\n" >>$ver_log;
     echo -e "device properties\n" >>$ver_log;
     for prop in ro.product.brand ro.product.model ro.build.product ro.product.device ro.build.description ro.build.fingerprint ro.product.cpu.abi ro.product.cpu.abilist; do
-        echo "$prop :- $(getprop $prop;)" >>$ver_log;
+        echo "$prop :- $(getprop $prop)" >>$ver_log;
     done;
-    echo -e "\n\n" >>$ver_log;
+    echo ' ' >>$ver_log; echo ' ' >>$ver_log;
     set +x; set -x 2>>$ver_log;
 fi;
 
 # Handle given arguments
-## see the README for what they do
 case $1 in -f|--force) force=true; shift; ;; esac;
 case $1 in
 
@@ -357,27 +389,25 @@ case $1 in
         test_refs; reset_perms;
         echo -e "- Battery status\n";
         echo "-- battery level :- $(batt_level)";
-        echo "-- battery health :- $(get_prop POWER_SUPPLY_HEALTH $(uevent_f);)";
-        status='Not charging'; if is_charging; then status=Charging; fi;
+        echo "-- battery health :- $(get_prop POWER_SUPPLY_HEALTH $(uevent_f))";
+        if is_charging; then status=Charging; else status='Not charging'; fi;
         echo -e "-- charging status :- $status\n";
-
         echo -e "- Current settings\n";
         echo "-- up threshold :- $(up_threshold)";
         echo "-- down threshold :- $(down_threshold)";
         echo -e "-- shut threshold :- $(shut_threshold)\n";
-
-        status=OFF; if $(auto_switch); then status=ON; fi;
+        if $(auto_switch); then status=ON; else status=OFF; fi;
         echo "-- automatic switching :- $status";
-        status=OFF; if $(auto_shut); then status=ON; fi;
+        if $(auto_shut); then status=ON; else status=OFF; fi;
         echo "-- automatic power-off :- $status";
-        status=OFF; if $(daemon_mode); then status=ON; fi;
+        if $(daemon_mode); then status=ON; else status=OFF; fi;
         echo -e "-- background daemon mode :- $status\n";
 
-        status='Not running'; if is_runningd; then status=Running; fi;
+        if is_runningd; then status=Running; else status='Not running'; fi;
         echo -e "-- daemon ( bg-activity ) status :- $status\n";
     ;;
 
-    -h|--help) show_help;
+    -h|--help) exit_help;
     ;;
 
     -rc|--reconf) set_ctrl_refs;
@@ -433,8 +463,7 @@ case $1 in
 
     --launch-daemon)
         while $(auto_shut) || $(auto_switch) && $(daemon_mode); do
-            if ! are_refs_set; then sleep 3; continue; fi;
-            reset_perms;
+            if ! are_refs_set; then sleep 2; continue; else reset_perms; fi;
 
             ## automatic power-off
             if $(auto_shut); then
@@ -449,7 +478,7 @@ case $1 in
                     if is_charging; then switch_ OFF; unset no_ckcurrent; fi;
                 elif [[ $(batt_level) -le $(down_threshold) ]]; then
                     if is_charging; then
-                        if [[ ! $no_ckcurrent && $(get_prop POWER_SUPPLY_CURRENT_NOW $(uevent_f);) -gt 0 ]]; then
+                        if [[ ! $no_ckcurrent && $(get_prop POWER_SUPPLY_CURRENT_NOW $(uevent_f)) -gt 0 ]]; then
                             switch_ OFF;
                         else
                             no_ckcurrent=true;
@@ -474,17 +503,18 @@ case $1 in
                 if [[ $2 -gt 20 || $2 -lt 5 ]]; then
                     if [[ ! $force ]]; then
                         abort 'Please give a level between 5 - 20';
+                    else
+                        test_bound $2;
                     fi;
-                    test_bound $2;
                 fi;
+                set_prop shut_threshold $2;
+                echo -e "- New value saved\n";
             else
                 abort 'Please give only numbers';
             fi;
         else
             abort 'Please give a threshold';
         fi;
-        set_prop shut_threshold $2;
-        echo -e "- New value saved\n";
     ;;
 
     -s|--switch)
@@ -506,8 +536,8 @@ case $1 in
 
     *)
         echo -e "- Heyyo fella, invalid option(s)\n";
-        sleep 1;
-        show_help;
+        sleep 2;
+        exit_help;
     ;;
 esac;
 exit 0;
