Sync with my personal Repo

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,6 +1,6 @@
 #!/sbin/sh
 # MC's Charging Controller
-# mcc Installer ( 201804102 )
+# mcc Installer ( 201804111 )
 # MCMotherEffin' @ XDA Developers
 
 # Copyright (c) 2018 Jaymin " MCMotherEffin' " Suthar. All rights reserved.
@@ -17,41 +17,30 @@
 ## by controlling charging, without any kind of WARRANTY, and I can not be
 ## held responsible for any damage, or just anything bad happened.
 
-# Finally, you should obtain a copy of the GNU GPL v3 from <http://gnu.org/licenses/>.
-
-# Some info about this file.
-
-# This file is the installer script which will be ran by Magisk Manager or
-## the recovery flashing the module. It firstly will do some detections to
-## figure out the environment, then dynamically detect Magisk mount point,
-## and set BusyBox up. It will then check if the device is compatible with
-## the module, and as recoveries ( mostly ) contain different kernel, them
-## flashing mcc is unwanted. If the check was a success, it'd then install
-## or uninstall the module based on the installtion status. And also while
-## installing, it will edit mcc.conf with the detected references.
+# Finally, you should have received a copy of the GPL v3 with mcc, if not,
+## see <http://gnu.org/licenses/>.
 
 if grep '^/sbin/sh' </proc/$$/cmdline >/dev/null; then
-    for message in ' ' '- mcc must be installed from booted Android, aborting...' ' '; do
+    for message in ' ' 'mcc: error: mcc requires Magisk Manager as medium' ' '; do
         echo -e "ui_print $message\nui_print" >>/proc/self/fd/$2;
     done;
     exit 1;
 elif [ "$(magisk -V)" -lt 1410 ]; then
     echo ' '; echo ' ';
-    echo -e "- mcc must be installed with Magisk >= 1410, aborting...\n"; exit 1;
-else
-    set -x; echo ' '; echo ' ';
+    echo -e "mcc: error: mcc requires Magisk >= 1410\n";
+    exit 1;
 fi;
+set -x; echo ' '; echo ' ';
 for magisk_bb in $(find /data -type f -name busybox | grep '/magisk/busybox$'); do
     if $magisk_bb | grep 'topjohnwu ' >/dev/null; then
         if image=$(ls ${magisk_bb%/*/*}/magisk.img); then
             for loop_device in /dev/block/loop*; do
                 if $magisk_bb losetup $loop_device | grep " $image$" >/dev/null; then
                     for real_mount_point in $(grep "^$loop_device " /proc/mounts | $magisk_bb awk '{ print $2 }' | grep -Ev '^/system|^/vendor'); do
-                        if ! grep '^com.google.android.gms.unstable$' $real_mount_point/.core/hidelist >/dev/null || ! test -d $real_mount_point/lost+found || ! test -d $real_mount_point/.core/service.d; then
-                            unset real_mount_point;
-                        else
+                        if grep '^com.google.android.gms.unstable$' $real_mount_point/.core/hidelist >/dev/null && test -d $real_mount_point/lost+found && test -d $real_mount_point/.core/service.d; then
                             break 3;
                         fi;
+                        unset real_mount_point;
                     done;
                 fi;
             done;
@@ -65,20 +54,20 @@ rm -rf $tmp_dir; mkdir -p $tmp_bin;
 cp -a $magisk_bb $tmp_bin/;
 $tmp_bin/busybox --install $tmp_bin/;
 export PATH=$tmp_bin:$PATH;
-if [ -z $magisk_bb ] || [ -z $real_mount_point ] || [ "$(which awk)" != $tmp_bin/awk ]; then
-    echo -e "- Failed to set environment via Magisk, aborting...\n"; exit 1;
+if [ -z $magisk_bb ] || [ -z $real_mount_point ] || [ -z "$(which awk)" ]; then
+    echo -e "mcc: error: Failed to detect Magisk environment\n"; exit 1;
 fi;
 zip_file="$3";
 tmp_file=$tmp_dir/cached;
-mount_point=/dev/mcc_img;
+mount_point=$tmp_dir/img;
 mod_dir=$mount_point/mcc;
 inst_mod_dir=$real_mount_point/mcc;
-lock_file=$inst_mod_dir/cache/lock_d;
+lock_file=$inst_mod_dir/cache/lock;
 image=${image%/*}/magisk_merge.img;
 
-abort() { printp "$1, aborting..."; exit 1; }
+abort() { echo -e "mcc: error: $1\n"; exit 1; }
 
-printp() { echo -e "- $1\n"; }
+printp() { echo -e "mcc: info: $1\n"; }
 
 get_prop() { sed -n "s/^$1=//p" $2; }
 
@@ -95,70 +84,69 @@ imgsize_test() {
 set_perm_recursive() {
     find $1 | while read entry; do
         chown 0:$2 $entry;
-        if [[ ! -d $entry ]]; then chmod $3 $entry; else chmod 0755 $entry; fi;
+        chmod $3 $entry;
+        if [[ -d $entry ]]; then chmod 0755 $entry; fi;
         chcon u:object_r:system_file:s0 $entry;
     done;
 }
 
-printp '------------------------------------------------'; echo ' ';
-printp "     MC's Charging Controller";
-printp "         by MCMotherEffin' @ XDA Developers";
-printp '------------------------------------------------'; echo ' ';
-echo ' '; echo ' '; echo ' ';
-printp 'Checking compatibility ( requires the battery be charging )...';
+echo '------------------------------------------------'; echo ' ';
+echo "     MC's Charging Controller";
+echo "         MCMotherEffin' @ XDA Developers";
+echo '------------------------------------------------'; echo ' ';
+echo ' '; echo ' ';
+printp 'Checking compatibility ( requires charging ON )...';
 sleep 3;
 find /sys/devices /sys/module -type f -name uevent >$tmp_file;
 if touch $lock_file; then no_file_logs=true mcc --enable >/dev/null; fi;
 i=1;
 while read uevent; do
-    if grep -q '^POWER_SUPPLY_NAME=.*[Bb]att.*$' $uevent; then
-        if is_charging; then
-            for ref in ${uevent%/*}/*; do
-                if [[ -f $ref ]]; then
-                    if ls -l $ref | grep -Eq '^[a-z-]+w[a-z-]* '; then
-                        case $(cat $ref) in
-                            1       ) c_ON=1;        c_OFF=0;        ;;
-                            0       ) c_ON=0;        c_OFF=1;        ;;
-                            on      ) c_ON=on;       c_OFF=off;      ;;
-                            off     ) c_ON=off;      c_OFF=on;       ;;
-                            true    ) c_ON=true;     c_OFF=false;    ;;
-                            false   ) c_ON=false;    c_OFF=true;     ;;
-                            enable  ) c_ON=enable;   c_OFF=disable;  ;;
-                            disable ) c_ON=disable;  c_OFF=enable;   ;;
-                            enabled ) c_ON=enabled;  c_OFF=disabled; ;;
-                            disabled) c_ON=disabled; c_OFF=enabled;  ;;
-                            *       ) continue;                      ;;
-                        esac;
-                        echo $c_OFF >$ref; sleep 1;
-                        if ! is_charging; then
-                            echo $c_ON >$ref; sleep 1;
-                            if is_charging; then
-                                eval switch_$i=\"$ref $c_ON $c_OFF\"; let i++;
-                                if [[ $i -eq 3 ]]; then break 2; fi;
+    if grep -q '^POWER_SUPPLY_NAME=.*[Bb]att.*$' $uevent && is_charging; then
+        while read eff_uevent; do
+            if (grep -q '^POWER_SUPPLY_NAME=.*[Bb]att.*$' $eff_uevent && grep -q '^POWER_SUPPLY_STATUS=[Cc]harging$' $eff_uevent) || grep -q '^DRIVER=.*[Cc]harger.*$' $eff_uevent; then
+                for ref in ${eff_uevent%/*}/*; do
+                    if [[ -f $ref ]]; then
+                        if ls -l $ref | grep -Eq '^[a-z-]+w[a-z-]* '; then
+                            case $(cat $ref) in
+                                1       ) c_ON=1;        c_OFF=0;        ;;
+                                0       ) c_ON=0;        c_OFF=1;        ;;
+                                on      ) c_ON=on;       c_OFF=off;      ;;
+                                off     ) c_ON=off;      c_OFF=on;       ;;
+                                true    ) c_ON=true;     c_OFF=false;    ;;
+                                false   ) c_ON=false;    c_OFF=true;     ;;
+                                enable  ) c_ON=enable;   c_OFF=disable;  ;;
+                                disable ) c_ON=disable;  c_OFF=enable;   ;;
+                                enabled ) c_ON=enabled;  c_OFF=disabled; ;;
+                                disabled) c_ON=disabled; c_OFF=enabled;  ;;
+                                *       ) continue;                      ;;
+                            esac;
+                            echo $c_OFF >$ref; sleep 1;
+                            if ! is_charging; then
+                                echo $c_ON >$ref; sleep 1;
+                                if is_charging; then
+                                    eval switch_$i=\"$ref $c_ON $c_OFF\";
+                                    let i++;
+                                    if [[ $i -eq 3 ]]; then break 3; fi;
+                                fi;
                             fi;
+                            echo $c_ON >$ref;
                         fi;
-                        echo $c_ON >$ref;
-                    else
-                        continue;
                     fi;
-                fi;
-            done;
-            if [[ $i -gt 1 ]]; then break; fi;
-        fi;
+                done;
+                if [[ $i -gt 1 ]]; then break 2; fi;
+            fi;
+        done <$tmp_file;
     fi;
 done <$tmp_file;
 rm -f $lock_file;
-if [[ $i -gt 1 ]]; then
-    printp OK; echo ' '; echo ' '; echo ' ';
-else
-    abort 'Failed the check';
-fi;
+if [[ $i -eq 1 ]]; then abort 'Failed the check'; fi;
+printp OK; echo ' '; echo ' ';
 if [[ -f $image ]]; then
-    printp "Found $image";
+    printp "$image exists";
     e2fsck -pf $image >&2;
     img_total=$(imgsize_test 2);
     if [[ $(imgsize_test 1) -eq $img_total ]]; then
-        printp "Resizing $image...";
+        printp "Expanding $image...";
         resize2fs $image $((img_total + 32))M;
     fi;
 else
@@ -180,24 +168,28 @@ for minor in 1 2 3 4 5 6 7; do
 done;
 if ! grep -q " $mount_point " /proc/mounts; then
     abort "Failed to mount $image";
-fi;
-if [[ $(get_prop versionCode $mod_dir/module.prop || which_installed) -ge 201804102 ]]; then
-    printp 'Same or newer installed, uninstalling to FATU...';
+elif [[ $(get_prop versionCode $mod_dir/module.prop || which_installed) -ge 201804111 ]]; then
+    printp 'Same or newer already installed, uninstalling...';
     kill $(ps | grep -v ' grep ' | grep ' {mcc} ' | awk '{ print $1 }' | tr '\n' ' ');
     rm -rf $mod_dir $inst_mod_dir /cache/mcc_e*.log;
-    if inst_mcc=$(ls /system/xbin/mcc /system/bin/mcc); then
+    if inst_mcc=$(ls /system/xbin/mcc /system/bin/mcc | head -1); then
         umount $inst_mcc; rm -f $inst_mcc; umount ${inst_mcc%/*};
     fi;
 else
     rm -rf $mod_dir; mkdir -p $mod_dir/docs $mod_dir/cache;
     printp 'Extracting mcc files...';
-    unzip -o "$zip_file" 'system/*' mcc.conf service.sh post-fs-data.sh module.prop -d $mod_dir >&2;
-    unzip -o "$zip_file" README.md -d $mod_dir/docs >&2;
+    unzip -o "$zip_file" 'system/*' post-fs-data.sh service.sh mcc.conf module.prop -d $mod_dir >&2;
+    unzip -o "$zip_file" LICENSE.md README.md -d $mod_dir/docs >&2;
+    bin_dir=$mod_dir/system/xbin;
     if [[ ! -d /system/xbin ]]; then
         mv $bin_dir $mod_dir/system/bin; bin_dir=$mod_dir/system/bin;
-    else
-        bin_dir=$mod_dir/system/xbin;
     fi;
+    set_prop uevent $uevent;
+    for i in 1 2; do
+        switch="$(eval echo \$switch_$i)";
+        if [[ -z $switch ]]; then break; fi;
+        set_prop switch_$i "$switch";
+    done;
     if [[ $(which_installed) -ge 201802251 ]]; then
         if old_conf=$(ls $inst_mod_dir/mcc.conf); then
             printp 'Restoring configurations...';
@@ -206,23 +198,14 @@ else
             done;
         fi;
     fi;
-    set_prop uevent $uevent;
-    for i in 1 2; do
-        switch="$(eval echo \$switch_$i)";
-        case $switch in
-            '') break;                        ;;
-            * ) set_prop switch_$i "$switch"; ;;
-        esac;
-    done;
-    touch $mod_dir/auto_mount;
     mkdir $inst_mod_dir;
-    touch $inst_mod_dir/update;
-    cp -f $mod_dir/module.prop $inst_mod_dir;
+    touch $mod_dir/auto_mount $inst_mod_dir/update;
+    cp -f $mod_dir/module.prop $inst_mod_dir/;
     printp 'Setting permissions...';
     set_perm_recursive $mod_dir    0 0644;
     set_perm_recursive $bin_dir 2000 0755;
 fi;
 umount $mount_point; losetup -d $loop_device;
-rmdir $mount_point; rm -rf $tmp_dir;
-printp Done; echo ' '; echo ' '; echo ' ';
+rm -rf $tmp_dir;
+printp Done; echo ' '; echo ' ';
 exit 0;
