Get rid of the useless superceded_yet thing

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,6 +1,6 @@
 #!/sbin/sh
 # My Charging Controller
-# mcc Install (201804181)
+# mcc Install (201804191)
 # JayminSuthar @ xda-developers
 
 # Copyright (c) 2018 Jaymin Suthar. All rights reserved.
@@ -19,14 +19,12 @@
 # You should already have received a copy of GPLv3 with mcc,
 ## if not, see <http://www.gnu.org/licenses/>.
 
-if [ ! $BOOTMODE ]; then
-    for line in ' ' 'mcc: error: mcc requires Magisk Manager installation' ' '; do
-        echo -e "ui_print $line\nui_print" >>/proc/self/fd/$2;
-    done;
+if test ! $BOOTMODE; then
     exit 1;
-elif ! util_funcs=$(ls /data/adb/magisk/util_functions.sh || ls /data/magisk/util_functions.sh) \
-    || test ! $(sed -n 's/^MAGISK_VER_CODE=//p' $util_funcs) -ge 1400; then
-    echo -e '\n\nmcc: error: mcc requires Magisk >= 1400\n'; exit 1;
+elif ! util_funcs=$(ls /data/adb/magisk/util_functions.sh || ls /data/magisk/util_functions.sh); then
+    exit 1;
+elif test ! $(sed -n 's/^MAGISK_VER_CODE=//p' $util_funcs) -ge 1400; then
+    exit 1;
 fi;
 set -x; echo -e '\n';
 zip_file="$3";
@@ -34,7 +32,7 @@ tmp_dir=/dev/mcc_tmp;
 tmp_file=$tmp_dir/tmp_f;
 merge_root=$tmp_dir/img;
 mod_dir=$merge_root/mcc;
-bin_dir=$mod_dir/system/xbin;
+sys_dir=$mod_dir/system;
 image=${util_funcs%/*/*}/magisk_merge.img;
 mount_point=$(find /sbin/.core/img /magisk -type d -maxdepth 0);
 main_mod_dir=$mount_point/mcc;
@@ -49,7 +47,7 @@ get_size() {
 set_perms() {
     find $1 | while read entry; do
         chown 0:$2 $entry;
-        chmod $3 $entry; if [ -d $entry ]; then chmod 0755 $entry; fi;
+        chmod $3 $entry; if test -d $entry; then chmod 0755 $entry; fi;
         chcon u:object_r:system_file:s0 $entry;
     done;
 }
@@ -57,22 +55,34 @@ rm -rf $tmp_dir; mkdir -p $merge_root;
 echo -e '-------------------------------------------------------------\n';
 echo "                    MC's Charging Controller                      ";
 echo -e '-------------------------------------------------------------\n\n\n';
-(export no_ver_logs=true; mcc --enable; sleep 6; mcc --clean) >/dev/null &
+(export no_ver_logs=true; mcc --enable; sleep 3; mcc --clean) >/dev/null &
 find /sys/devices /sys/module -type f -name uevent >$tmp_file &
-printp 'Checking compatibility (requires charging ON)...'; sleep 6;
-wait; i=1;
+printp 'Checking compatibility (requires charging ON)...';
+wait;
+if test -f /cache/mcc_noo; then only_system=true; fi;
+i=1;
 while read uevent; do
     chmod u+r $uevent;
-    if grep -q '^POWER_SUPPLY_NAME=.*[Bb]att' $uevent \
-    && grep -q '^POWER_SUPPLY_STATUS=[Cc]harging$' $uevent \
-    && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $uevent; then
+    if grep -q '^POWER_SUPPLY_NAME=.*[Bb]att' $uevent; then
         while read eff_uevent; do
             chmod u+r $eff_uevent;
-            if grep -Eq '^POWER_SUPPLY_NAME=.*([Bb]att|USB|usb)' $eff_uevent \
-            || grep -Eq '^DRIVER=.*[Cc]harg(er|ing)' $eff_uevent; then
+            if grep -Eq '^POWER_SUPPLY_NAME=.*([Bb]att|USB|usb)' $eff_uevent; then
+                proceed=true;
+            elif grep -Eq '^DRIVER=.*[Cc]harg(er|ing)' $eff_uevent; then
+                proceed=true;
+            fi;
+            if test $proceed; then
+                unset proceed;
                 for ref in ${eff_uevent%/*}/*; do
-                    if test -f $ref && chmod u+r $ref && ls -l $ref | grep -Eq '^\-[rx\-]+w[rwx\-]* ' \
-                    && (test ! -f /cache/mcc_noo || ls -l $ref | grep -Eq ' system | radio '); then
+                    if test ! -f $ref; then
+                        skip=true;
+                    elif ! ls -l $ref | grep -Eq '^\-[rx\-]+w[rwx\-]* '; then
+                        skip=true;
+                    elif test $only_system && ! ls -l $ref | grep -Eq ' system | radio '; then
+                        skip=true;
+                    fi;
+                    if test ! $skip; then
+                        chmod u+r $ref;
                         case "$(cat $ref)" in
                             1       ) c_ON=1;        c_OFF=0;        ;;
                             0       ) c_ON=0;        c_OFF=1;        ;;
@@ -86,29 +96,30 @@ while read uevent; do
                             disabled) c_ON=disabled; c_OFF=enabled;  ;;
                             *       ) continue;                      ;;
                         esac;
-                        echo $c_OFF >$ref; sleep 1;
+                        echo $c_OFF >$ref; sleep 0.6;
                         if ! is_charging; then
-                            echo $c_ON >$ref; sleep 1;
+                            echo $c_ON >$ref; sleep 0.6;
                             if is_charging; then
                                 eval switch_$i=\"$ref $c_ON $c_OFF\"; let i++;
-                                if [ $i -eq 3 ]; then break 3; fi;
+                                if test $i -eq 3; then break 3; fi;
                             fi;
                         fi;
                         echo $c_ON >$ref;
                     fi;
+                    unset skip;
                 done;
-                if [ $i -gt 1 ]; then break 2; fi;
+                if test $i -gt 1; then break 2; fi;
             fi;
         done <$tmp_file;
     fi;
 done <$tmp_file;
-if [ $i -eq 1 ]; then abort 'Failed the check'; fi;
+if test $i -eq 1; then abort 'Failed the check'; fi;
 printp OK; echo -e '\n';
-if [ -f $image ]; then
+if test -f $image; then
     printp "$image exists";
     e2fsck -pf $image >&2;
     img_total=$(get_size 2);
-    if [ $(get_size 1) -eq $img_total ]; then
+    if test $(get_size 1) -eq $img_total; then
         printp "Expanding $image...";
         resize2fs $image $((img_total + 32))M;
     fi;
@@ -128,20 +139,25 @@ done;
 if ! grep -q " $merge_root " /proc/mounts; then
     abort "Failed to mount $image";
 fi;
-rm -rf $mod_dir; mkdir -p $mod_dir/docs $main_mod_dir;
+rm -rf $mod_dir;
+mkdir -p $mod_dir/docs $main_mod_dir;
 printp 'Extracting mcc files...';
 unzip -o "$zip_file" 'system/*' 'files/*' post-fs-data.sh service.sh module.prop -d $mod_dir >&2;
 unzip -o "$zip_file" COPYING README.md -d $mod_dir/docs >&2;
-if [ ! -d /system/xbin ]; then
-    mv $bin_dir $mod_dir/system/bin; bin_dir=$mod_dir/system/bin;
+if test ! -d /system/xbin; then
+    mv $sys_dir/xbin $sys_dir/bin;
 fi;
 set_prop uevent $uevent;
 for i in 1 2; do
     switch="$(eval echo \$switch_$i)";
-    if [ ! -z "$switch" ]; then set_prop switch_$i "$switch"; fi;
+    if test -n "$switch"; then set_prop switch_$i "$switch"; fi;
 done;
-if test $(get_prop versionCode $main_mod_dir/module.prop || echo 0) -ge 201804171 \
-&& old_conf=$(ls $main_mod_dir/files/secure/mcc.conf); then
+if test $(get_prop versionCode $main_mod_dir/module.prop || echo 0) -lt 201804171; then
+    no_restore=true;
+elif ! old_conf=$(ls $main_mod_dir/files/secure/mcc.conf); then
+    no_restore=true;
+fi;
+if test ! $no_restore; then
     printp 'Restoring configurations...';
     for prop in auto_shut auto_switch up_threshold down_threshold shut_threshold; do
         set_prop $prop $(get_prop $prop $old_conf);
@@ -150,7 +166,7 @@ fi;
 touch $mod_dir/auto_mount $main_mod_dir/update;
 cp -f $mod_dir/module.prop $main_mod_dir/;
 printp 'Setting permissions...';
-set_perms $mod_dir 0 0644; set_perms $bin_dir 2000 0755;
+set_perms $mod_dir 0 0644; set_perms $sys_dir/* 2000 0755;
 umount $merge_root; losetup -d $loop_device;
 rm -rf $tmp_dir;
 printp Done; echo -e '\n';
