Sync with my personal Repo

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,6 +1,6 @@
 #!/sbin/sh
 # My Charging Controller
-# mcc Install (201804151)
+# mcc Install (201804161)
 # JayminSuthar @ xda-developers
 
 # Copyright (c) 2018 Jaymin Suthar. All rights reserved.
@@ -24,8 +24,8 @@ if [ ! $BOOTMODE ]; then
         echo -e "ui_print $line\nui_print" >>/proc/self/fd/$2;
     done;
     exit 1;
-elif ! util_funcs=$(ls /data/adb/magisk/util_functions.sh || ls /data/magisk/util_functions.sh) || test ! $(sed -n 's/^MAGISK_VER_CODE=//p' $util_funcs) -ge 1410; then
-    echo -e '\n\nmcc: error: mcc requires Magisk >= 1410\n'; exit 1;
+elif ! util_funcs=$(ls /data/adb/magisk/util_functions.sh || ls /data/magisk/util_functions.sh) || test ! $(sed -n 's/^MAGISK_VER_CODE=//p' $util_funcs) -ge 1400; then
+    echo -e '\n\nmcc: error: mcc requires Magisk >= 1400\n'; exit 1;
 fi;
 set -x; echo -e '\n';
 zip_file="$3";
@@ -56,8 +56,7 @@ echo -e '-------------------------------------------------------------\n';
 echo "                    MC's Charging Controller                      ";
 echo -e '-------------------------------------------------------------\n\n\n';
 printp 'Checking compatibility (requires charging ON)...'; sleep 3;
-find /sys/devices /sys/module -type f -name uevent | grep -E '[Bb]att|[Cc]harg' >$tmp_file;
-export no_ver_logs=true; (mcc --enable; sleep 2; mcc --clean) >/dev/null;
+find /sys/devices /sys/module -type f -name uevent >$tmp_file;
 i=1;
 while read uevent; do
     if grep -q '^POWER_SUPPLY_NAME=.*[Bb]att' $uevent && grep -Eq '^POWER_SUPPLY_CURRENT_NOW=[0-9\-]+$' $uevent; then
@@ -133,7 +132,7 @@ for i in 1 2; do
     switch="$(eval echo \$switch_$i)";
     if [[ ! -z "$switch" ]]; then set_prop switch_$i "$switch"; fi;
 done;
-if test $(get_prop versionCode $main_mod_dir/module.prop || echo 0) -ge 201804151 && old_conf=$(ls $main_mod_dir/files/secure/mcc.conf); then
+if test $(get_prop versionCode $main_mod_dir/module.prop || echo 0) -ge 201804161 && old_conf=$(ls $main_mod_dir/files/secure/mcc.conf); then
     printp 'Restoring configurations...';
     for prop in auto_shut auto_switch up_threshold down_threshold shut_threshold; do
         set_prop $prop $(get_prop $prop $old_conf);
